### ISSUE TITLE
Does this work for Mac OS?

### ISSUE THREAD

**Issue by bizfreak22** [harismuneer/Ultimate-Facebook-Scraper#1]
I set it up with the newest Chrome Driver, but get an error. When I looked at the code it looks for Linux or Windows, not Unix..just wanted to ask.

Thanks!

**Comment by harismuneer** [comment]
Hi bizfreak.
Can you please share the screenshot of the error?

**Comment by harismuneer** [comment]
Thanks elievischel for confirming!

**Comment by haemi** [comment]
how did you install the chrome driver for mac?
