### ISSUE TITLE
Does this work on pages? 

### ISSUE THREAD

**Issue by dwjohnston** [harismuneer/Ultimate-Facebook-Scraper#10]
I am more interested in scraping the comments of public facebook pages. Does this work for this?

**Comment by github-userx** [comment]
I don't think that's possible with UFS yet.

Have you seen this one?

> **Facebook Scraper For Multiple Pages**
***Scrape multiple public Facebook pages en masse to help yield social analytics.***
>
>https://github.com/jpryda/facebook-multi-scraper/
>
>What can be collected from public page posts?
>
>Post ID, Publish Date, Post Type, Headline, Shares, Reactions, **Comments**, Caption, Link
