### ISSUE TITLE
Photos not getting downloaded

### ISSUE THREAD

**Issue by billmdev** [harismuneer/Ultimate-Facebook-Scraper#100]
**Description**
Photos of every category(Uploaded, Tagged, Following's) and videos are not downloaded but the rest of information(text data) about a person is.

**To Reproduce**
1. Followed normal installation steps as asked on the README
2. Run 'python scraper/scraper.py     --uploaded_photos True  
   --friends_photos True     --friends_small_size True     --photos_small_size True     --total_scrolls 2500 --scroll_time 8'
3. Scrapes data normally
4. But photos are not downloaded

**Expected behavior**
Normally folders of different categories of photos are to be created on the local machine and downloaded.

**Desktop (please complete the following information):**
 - OS: Linux(Ubuntu 16.04)
 - Python version 3.7.5
 - Chrome web driver version 80

**Comment by thg6060** [comment]
same problem

**Comment by sinepgnol** [comment]
same problem as well

**Comment by billmdev** [comment]
Solved!

**Comment by billmdev** [comment]
Solved!

**Comment by badarshahzad** [comment]
@billmdev  how did you solve this problem could you please enlighten me about this?

**Comment by billmdev** [comment]
@badarshahzad In which language is your facebook?

**Comment by badarshahzad** [comment]
Well, I didn't get your question but for information I developed my own scrapper in Java

**Comment by billmdev** [comment]
I meant by language of Facebook on your profile. What I did was edited some elements and changed my language to English.

**Comment by badarshahzad** [comment]
My profile language is English but I didn't make any amendment.


Thank you @billmdev for your concern and time to reply my question.

**Comment by billmdev** [comment]
You're welcome @badarshahzad. Have you tested finally? Is everything is ok?
