### ISSUE TITLE
Remove credentials.yaml

### ISSUE THREAD

**Issue by harismuneer** [harismuneer/Ultimate-Facebook-Scraper#107]
Currently the username and password of a user's FB profile is read from the crendentials.yaml file.

This file accidently gets committed by some users and is a security threat. Thats why this file should be removed and instead the username and password should be passed as command line arguments to the scraper.py.

This requires a minor change and hopefully wont take much time. So just start gentleman! :)

**Comment by VikashKothary** [comment]
I'd recommend using a `.env` instead.
