### ISSUE TITLE
Likes, Reactions, Shares, and Comments

### ISSUE THREAD

**Issue by jewl123** [harismuneer/Ultimate-Facebook-Scraper#11]
Hii !

I am trying to capture the number of likes/reactions, shares, and comments from a profile.
I have tried a few implementations and cannot seem to make it work :(

For instance, the number of likes/reactions has a changing ID tag. How is this properly written in Selenium ?

Thank You :)

**Comment by kaizoApps** [comment]
Hi, there i am also interested in that kind of functionality.
Concrete use case would be: Scrape me the likes from 1000 fans of this fb page: https://www.facebook.com/CocaColaDE/

**Comment by harismuneer** [comment]
Currently UFS doesn't scrape these things. However, I am always open to contributions, so you can guys can give it a try and generate a pull request :)
