### ISSUE TITLE
Input File empty

### ISSUE THREAD

**Issue by ogahozy** [harismuneer/Ultimate-Facebook-Scraper#110]
I add a friend profile to the input.txt, add my credentials to the .yaml
But when I run the code, i got "Input file is empty "

Do i need to setup any other thing?

**Comment by stiwari2** [comment]
Same bug. After I setup UFS (2FA, yaml and input.txt) and ran python3 scraper/scraper.py, got message that "Input file is empty "

**Comment by tridelt** [comment]
try delete the first line --> `#Lines starting with # and empty lines will be ignored`
that worked for me

cheers!

**Comment by ogahozy** [comment]
another error after removing the first line

{'uploaded_photos': True, 'friends_photos': True, 'friends_small_size':
True, 'photos_small_size': True, 'total_scrolls': 2500, 'scroll_time': 8}


 Starting Scraping...
/bin/sh: 1: google-chrome: not found
There's some error in log in.

 <class 'TypeError'>

**Comment by ManuelBanza** [comment]
Hi.
I have the same problem

**Comment by DrWhax** [comment]
You can use a workaround for that as well:

edit all mentions of google-chrome and turn it into chromium if you're more into that:

```
venv/lib/python3.7/site-packages/webdriver_manager/utils.py
```

Then it continues and goes to install and unpack the chromedriver:

```
Starting Scraping...
Trying to download new driver from http://chromedriver.storage.googleapis.com/80.0.3987.106/chromedriver_linux64.zip
Unpack archive /home/user/.wdm/drivers/chromedriver/80.0.3987.106/linux64/chromedriver.zip
```

**Comment by billmdev** [comment]
@ogahozy when your issue is solved please close the issue as solved and create a new one. What you posed in the comments is a completely unrelated issue from this one.

**Comment by ManuelBanza** [comment]
> You can use a workaround for that as well:
> 
> edit all mentions of google-chrome and turn it into chromium if you're more into that:
> 
> ```
> venv/lib/python3.7/site-packages/webdriver_manager/utils.py
> ```
> 
> Then it continues and goes to install and unpack the chromedriver:
> 
> ```
> Starting Scraping...
> Trying to download new driver from http://chromedriver.storage.googleapis.com/80.0.3987.106/chromedriver_linux64.zip
> Unpack archive /home/user/.wdm/drivers/chromedriver/80.0.3987.106/linux64/chromedriver.zip
> ```

Hi @DrWhax is this for the first or second problem in this issue? 
Thanks

**Comment by DrWhax** [comment]
> > You can use a workaround for that as well:
> > edit all mentions of google-chrome and turn it into chromium if you're more into that:
> > ```
> > venv/lib/python3.7/site-packages/webdriver_manager/utils.py
> > ```
> > 
> > 
> > Then it continues and goes to install and unpack the chromedriver:
> > ```
> > Starting Scraping...
> > Trying to download new driver from http://chromedriver.storage.googleapis.com/80.0.3987.106/chromedriver_linux64.zip
> > Unpack archive /home/user/.wdm/drivers/chromedriver/80.0.3987.106/linux64/chromedriver.zip
> > ```
> 
> Hi @DrWhax is this for the first or second problem in this issue?
> 
> I deleted the first line and the scraping goes on, but the file is empty, just has column names.
> 
> Thanks

2nd

**Comment by talhalatiforakzai** [comment]
Open fbcrawl.py and then click on the file for editing and reformat the code using ( ctrl+alt+L) and save it, this will solve the issue.

**Comment by Taylander** [comment]
had the same issue.

deleting `#Lines starting with # and empty lines will be ignored`

removed the "empty input.txt file" error.

**Comment by kristidon** [comment]
I have the same issue, even after removing `#Lines starting with # and empty lines will be ignored` from input.txt, this is what follows: 
`{'uploaded_photos': True, 'friends_photos': True, 'friends_small_size': True, 'photos_small_size': True, 'total_scrolls': 2500, 'scroll_time': 8}
Input file is empty.`

**Comment by Cabbache** [comment]
I fixed this by changing line 799 in scraper.py from `for line in open("input.txt", newline="\r\n")` to `for line in open("input.txt", newline="\n")`. This however, may not work for everyone.

**Comment by elig0n** [comment]
To overcome the second problem I replaced line 740 in scraper.py to:

                executable_path="/usr/bin/chromedriver", options=options

put your own `chromedriver` location in executable_path. 
There is no need to modify the webdriver_manager library for that

**Comment by harismuneer** [comment]
### 📢 Important Announcement: UFS 2.0 (with support for latest Facebook UI)

Hi guys! The exclusive version of **UFS 2.0** supports scraping for the latest Facebook UI along with many powerful features, much better organization through CSV (Excel-like) file format, bug fixes, and multiple browser support. You can get exclusive access here: 

#### **[Buy UFS 2.0](https://tinyurl.com/UFS-NEW)** 

Building the new version has been a tough technical challenge and I have spent a considerable amount of time and effort on building it. Therefore, kindly support by purchasing it from the link shared [above.](https://tinyurl.com/UFS-NEW) 

<hr>
You can also share small donations through these links:


- <a href="https://buy.paddle.com/product/638653"><b>Platinum (99.99$)</b> -> 2 hours of development<a/>
- <a href="https://buy.paddle.com/product/638651"><b>Gold (49.99$)</b> -> 1 hour of development</a>
- <a href="https://buy.paddle.com/product/638654"><b>Silver (19.99$)</b> -> 30 minutes of development</a>

_If **considerable support is shown through the above donations then I will release the version for the general public** after some time as I want to keep this software open-sourced. So, now is the time for all those folks who benefited from the tool to support its reach for a wider audience :)_

<hr>
