### ISSUE TITLE
Groups link parsed as a Profile links

### ISSUE THREAD

**Issue by bydioeds** [harismuneer/Ultimate-Facebook-Scraper#111]
When I try to get groups, their links are parsed as profile links.

For example the following link `https://www.facebook.com/groups/xxxxxxxx` is converted to `https://www.facebook.com/xxxxxxxx` so when using `identify_url()` it always returns 0.

the solution is to change `facebook_https_prefix + facebook_link_body + get_item_id (line)` from line 798 in `scraper/scraper.py` to `line` it doesn't seem like doing this breaks things, profiles keep working.

https://github.com/harismuneer/Ultimate-Facebook-Scraper/blob/48483a4019ddd9d17bc6de9bc1ae57ad83408324/scraper/scraper.py#L797-L801

**Comment by sunnyhasija** [comment]
Did you ever find a resolution to this?
