### ISSUE TITLE
There's some error in log in. <class 'TypeError'>

### ISSUE THREAD

**Issue by syedmohaiman** [harismuneer/Ultimate-Facebook-Scraper#118]
Hello guys

I am receiving:
**Starting Scraping...
'reg' is not recognized as an internal or external command,
operable program or batch file.
There's some error in log in.
<class 'TypeError'>**

Do you have an idea of how I possibly can fix it?

 - OS: [Windows]
 - Python version [3.8.2]
 - Chrome web driver version [83.0.4103.14]

**Comment by samdsox** [comment]
I also received this error. I did a little testing (printing out exception errors and such) and followed the traceback to the webdriver.py file.
  

>   raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: crashed.
>   (unknown error: DevToolsActivePort file doesn't exist)

 It looks like chrome crashes after execute. I think this is an artifact of using WSL, as chrome does not run natively on WSL without some tinkering. Our best bet at the moment is probably to run this off of linux rather than WSL.

**Comment by dfir-rick** [comment]
This fix is not working for me.  Are there any other possible solutions to this error?

py scraper\scraper.py
{'uploaded_photos': True, 'friends_photos': True, 'friends_small_size': True, 'photos_small_size': True, 'total_scrolls': 2500, 'scroll_time': 8}

Starting Scraping...
There's some error in log in.
<class 'TypeError'>

**Comment by Deepi-cyber** [comment]
{'uploaded_photos': True, 'friends_photos': True, 'friends_small_size': True, 'photos_small_size': True, 'total_scrolls': 2500, 'scroll_time': 8}

Starting Scraping...
There's some error in log in.
<class 'TypeError'>
only this error coming i dont how to suppress it

**Comment by jasonkwan1** [comment]
same

**Comment by ksahmed** [comment]
same but with headless mode

**Comment by papaya-ais** [comment]
Did you add options to scraper.py?
I added argument

options.add_argument('--single-process')

and it caused the same error.
I fixed this removing while removing selenium options and testing

OS: [Ubuntu16.04]
Python version [3.7.0]
Chrome web driver version [85.0.4183.102]

**Comment by harismuneer** [comment]
@papaya-ais I see you are helping out on resolving multiple issues threads. Keep up the good work my friend 👍

**Comment by harismuneer** [comment]
### 📢 Important Announcement: UFS 2.0 (with support for latest Facebook UI)

Hi! The exclusive version of **UFS 2.0** supports scraping for the latest Facebook UI along with many powerful features, much better organization through CSV (Excel-like) file format, bug fixes, and multiple browser support. You can get exclusive access here: 

#### **[Buy UFS 2.0](https://tinyurl.com/UFS-NEW)** 

Building the new version has been a tough technical challenge and I have spent a considerable amount of time and effort on building it. Therefore, kindly support by purchasing it from the link shared [above.](https://tinyurl.com/UFS-NEW) 

<hr>
You can also share small donations through these links:


- <a href="https://buy.paddle.com/product/638653"><b>Platinum (99.99$)</b> -> 2 hours of development<a/>
- <a href="https://buy.paddle.com/product/638651"><b>Gold (49.99$)</b> -> 1 hour of development</a>
- <a href="https://buy.paddle.com/product/638654"><b>Silver (19.99$)</b> -> 30 minutes of development</a>

_If **considerable support is shown through the above donations then I will release the version for the general public** after some time as I want to keep this software open-sourced. So, now is the time for all those folks who benefited from the tool to support its reach for a wider audience :)_
