### ISSUE TITLE
Using a \n ending file instead of a \r\n for input.txt, will cause problems.

### ISSUE THREAD

**Issue by xNinjaKittyx** [harismuneer/Ultimate-Facebook-Scraper#120]
**Describe the bug**
I'm using this tool on linux. I had `input.txt` using `\n` endings instead of `\r\n` which causes it to read the entire file as a single url due to this line in the code:

https://github.com/harismuneer/Ultimate-Facebook-Scraper/blob/v2.0/scraper/scraper.py#L799

I fixed it myself using something like this

```
    urls = [
        facebook_https_prefix + facebook_link_body + get_item_id(line.strip())
        for line in io.open("input.txt", "r", newline="")  # Support both \n and \r\n endings.
        if not line.lstrip().startswith("#") and not line.strip() == ""
    ]
```
I can raise a pr if adding `import io` is ok.
This properly works for any \r or \n or \r\n ending file.

**To Reproduce**
Create an input.txt file with \n endings and run the code. You'll end up with 1 URL in `urls` variable.

**Expected behavior**
Should be separated properly

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Python version 3.8
 - Chrome web driver version: 81

**Additional context**

**Comment by harismuneer** [comment]
@xNinjaKittyx, great observation! Please generate a PR :)
