### ISSUE TITLE
Posts.txt contains ids but not posts

### ISSUE THREAD

**Issue by gustavoghp87** [harismuneer/Ultimate-Facebook-Scraper#123]
Hey guys,
I noticed that the mining file "Posts.txt" retrieves the main data from posts but I wanted to download the posts per se.

Am I doing something wrong?

Nevertheless, I wrote a python program that fetch the posts contain from ids in Posts.txt and exports to .xlsx in 4 columns: date, post url, post content and links in post, I could merge it.

**Comment by harismuneer** [comment]
@gustavoghp87 sure feel free to generate a PR.

**Comment by gustavoghp87** [comment]
Ready. Another question.., I noticed that chrome collapses when scrolls several times, takes about 2300 posts maximum.

Any solution?

**Comment by harismuneer** [comment]
> Ready. Another question.., I noticed that chrome collapses when scrolls several times, takes about 2300 posts maximum.
> 
> Any solution?

#165
