### ISSUE TITLE
Selenium + import-im6.q16

### ISSUE THREAD

**Issue by kernelshock** [harismuneer/Ultimate-Facebook-Scraper#125]
Hi there, i allready satisfy all dependencies, and follow the step by step in readme.md, but iǘe got this error message:
mxz@kali:~/Extra_Tools/Ultimate-Facebook-Scraper/scraper$ ./scraper.py
import-im6.q16: unable to grab mouse `': No existe el fichero o el directorio @ error/xwindow.c/XSelectWindow/9182.
import-im6.q16: unable to grab mouse `': No existe el fichero o el directorio @ error/xwindow.c/XSelectWindow/9182.
from: can't read /var/mail/selenium
from: can't read /var/mail/selenium.common.exceptions
from: can't read /var/mail/selenium.webdriver.chrome.options
from: can't read /var/mail/selenium.webdriver.common.by
from: can't read /var/mail/selenium.webdriver.support
from: can't read /var/mail/selenium.webdriver.support.ui
from: can't read /var/mail/webdriver_manager.chrome
./scraper.py: línea 18: error sintáctico cerca del elemento inesperado `('
./scraper.py: línea 18: `def get_facebook_images_url(img_links):'
Help me please!

**Comment by harismuneer** [comment]
Hello, have you ensured that the account from which you are logging in is using English as the default language for Facebook? Otherwise you can give the latest version a try.

**Comment by harismuneer** [comment]
### 📢 Important Announcement: UFS 2.0 (with support for latest Facebook UI)

Hi guys! The exclusive version of **UFS 2.0** supports scraping for the latest Facebook UI along with many powerful features, much better organization through CSV (Excel-like) file format, bug fixes, and multiple browser support. You can get exclusive access here: 

#### **[Buy UFS 2.0](https://tinyurl.com/UFS-NEW)** 

Building the new version has been a tough technical challenge and I have spent a considerable amount of time and effort on building it. Therefore, kindly support by purchasing it from the link shared [above.](https://tinyurl.com/UFS-NEW) 

<hr>
You can also share small donations through these links:


- <a href="https://buy.paddle.com/product/638653"><b>Platinum (99.99$)</b> -> 2 hours of development<a/>
- <a href="https://buy.paddle.com/product/638651"><b>Gold (49.99$)</b> -> 1 hour of development</a>
- <a href="https://buy.paddle.com/product/638654"><b>Silver (19.99$)</b> -> 30 minutes of development</a>

_If **considerable support is shown through the above donations then I will release the version for the general public** after some time as I want to keep this software open-sourced. So, now is the time for all those folks who benefited from the tool to support its reach for a wider audience :)_
