### ISSUE TITLE
selenium.common.exceptions.NoSuchElementException

### ISSUE THREAD

**Issue by tf0884** [harismuneer/Ultimate-Facebook-Scraper#129]
**Describe the bug**
The code starts Google Chrome, navigates successfully to facebook and enters credentials.  The Chrome window passes through the profiles listed correctly.  However, the following error messages appear in the command line:

Scraping Friends..
Exception (scrape_data) 0 Status = 0 <class 'selenium.common.exceptions.NoSuchElementException'>
...

Scraping Photos..
Exception (scrape_data) 0 Status = 1 <class 'selenium.common.exceptions.NoSuchElementException'>

Scraping About..
Exception (save_to_file) Status = 3 <class 'IndexError'>

A profile folder is created in "Data", containing txt files, but they are blank and there is no folder containing photos.

**To Reproduce**
Windows 10 
Updated Chrome.  Version 83.0.4103.97 (Official Build) (64-bit)
Python version 3.8.2

Follow readme.md instructions

**Comment by bipinpanwar55** [comment]
I am also facing the same issue.

**Comment by Rahulsunny11** [comment]
I am also facing the same issue

**Comment by raviyo** [comment]
I am also facing the same issue
@harismuneer

**Comment by Oli-BF** [comment]
Had the same issue, switched to the classic FB UI and worked no problem.

**Comment by Laura2797** [comment]
> Had the same issue, switched to the classic FB UI and worked no problem.

Hello, could you scrap anything about friends? when I run the program said:
Scraping Friends..
Friends Done!

But is not true, there's no information of friends in the profile carpet.

**Comment by Taylander** [comment]
Exact same bug here:

windows 10
python 3.8

[WDM] - Current google-chrome version is 83.0.4103
[WDM] - Get LATEST driver version for 83.0.4103
[WDM] - Driver [C:\Users\Sacace Pharma\.wdm\drivers\chromedriver\win32\83.0.4103.39\chromedriver.exe] found in cache

**Comment by pinsleepe** [comment]
Switching to classic UI didn't help to get rid of `NoSuchElementException` or `IndexError`. It removed only `WebDriverException` byr .txt files are still empty.

**Comment by nvanderperren** [comment]
I have also this bug.

**Comment by pawan-saxena** [comment]
I am wonder-struck that how this repo got so many stars (most probably paid or  fake ones ).
Thing is, Facebook removed the option to switch to classic, and the code written depends upon class and id tags which are there in the classic UI of Facebook.

Now in that case too, Facebook updates the tags frequently which requires the maintainers to actually update that info here in the code and being starred by so many and having made such big claims in read.me they check and do it every day.

I am sad  that  maintainers are very irresponsible.

So now you have left with two options, go edit the tags manually by yourself., which is a hassle as Facebook is updating them every  week, someone needs to take up this job.

**Comment by feathered-arch** [comment]
>
> someone needs to take up this job.
>


Cool. I look forward to seeing your progress so you quit your bitching
about free software.

Feel free to reach out if you need code review before you submit a pull
request.

**Comment by feathered-arch** [comment]
> `options.add_argument("headless")` - commented out at line 736
> 
> What it does is that it tricks the Facebook by modifying the header info and sends the request as if the user's browser doesn't support new web elements and sends you the old version by itself. (I don't know till when it will work but as of now it works )
> 
> Cheers ✌🏻

Have a look at this implementation in https://github.com/anoduck/UFS-quackified -- it does what you do without the need for a chrome plugin. I changed the agent below to something that gives you the old Facebook.

I also find this version to be a great fork if you are doing a lot of scraping. It allows for greater control of the scraping speed so you don't trigger Facebook's algorithms as easily.

______________________________

# Global Variables
opts = Options()
opts.add_argument(
    "user-agent=Mozilla/5.0 (Windows; U; MSIE 9.0; Windows NT 6.1; Win64; x64; Trident/5.0; .NET CLR 2.4.50725; .NET4.0E; en-AU)"

# If you change this variable the scraping process will change
# and not all elements will be scraped.
# Variable is archaic and deprecated
# driver = None
# driver = webdriver.Chrome(options=opts)

**Comment by pawan-saxena** [comment]
Thank you thing is i just found facebook is updating the tags after every 24 hours for those users who actually triggered the spam algorithms on their end.

I am working on a solution and will update you soon.
