### ISSUE TITLE
Can't get anything from scraping. <class 'selenium.common.exceptions.NoSuchElementException'>

### ISSUE THREAD

**Issue by raviyo** [harismuneer/Ultimate-Facebook-Scraper#130]
I've execute all the steps and the scraping is running, but after it finished, i got nothing, only the folders created and its empty. I've read the notes that the 'divs' of facebook is frequently changed and the interface is also changed too.

What i want to ask is, which python codes in what python files that i should changed and how do i look for the latest facebook's 'divs' so i can run the scraper?
Please someone help me for the issues, thanks

 - OS: Microsoft
 - Python version 3.8

**Comment by manoj-nain** [comment]
Same Here. Did not got any data. No folders created. Only a few empty text files.

**Comment by Oli-BF** [comment]
Had the same issue, switched to the classic UI and worked no problem.

**Comment by Rahulsunny11** [comment]
how to switch to classic FB UI

**Comment by manoj-nain** [comment]
What is that can you explain please

> Had the same issue, switched to the classic FB UI and worked no problem.

What is it can you please explain.

**Comment by Rahulsunny11** [comment]
> Had the same issue, switched to the classic FB UI and worked no problem.

I got it, thank you!


> What is that can you explain please
> 
> > Had the same issue, switched to the classic FB UI and worked no problem.
> 
> What is it can you please explain.

https://www.facebook.com/help/645404059595478
follow this link

**Comment by raviyo** [comment]
Thank

> 
> 
> > Had the same issue, switched to the classic FB UI and worked no problem.
> 
> I got it, thank you!
> 
> > What is that can you explain please
> > > Had the same issue, switched to the classic FB UI and worked no problem.
> > 
> > 
> > What is it can you please explain.
> 
> https://www.facebook.com/help/645404059595478
> follow this link

Woahh thanks, it worked!
