### ISSUE TITLE
Got no content in Posts.txt

### ISSUE THREAD

**Issue by RachelLYY** [harismuneer/Ultimate-Facebook-Scraper#132]
**Describe the bug**
After finishing scraping, the Posts.txt only got one line like this ' TIME || TYPE  || TITLE || STATUS  ||   LINKS(Shared Posts/Shared Links etc) || POST_ID'. 
<img width="640" alt="Screenshot 2020-06-09 at 6 29 14 PM" src="https://user-images.githubusercontent.com/20517959/84137367-2f56af00-aa7f-11ea-99e8-661bff52e01d.png">

**To Reproduce**
1. In Input.txt, only write one line, 'https://www.facebook.com/zuck'. 
2. Run 'python scraper/scraper.py'
3. No error is exported

**Desktop (please complete the following information):**
 - OS: macOS
 - Python version: 3.6
 - Chrome web driver version: 83.0.4103

**Additional context**
About the Posts.txt, how can I get all of the content?

**Comment by sunnyhasija** [comment]
I am getting the same error. 

Any update on how to fix it ?
