### ISSUE TITLE
NameError: name 'facebook_https_prefix' is not defined

### ISSUE THREAD

**Issue by pvita** [harismuneer/Ultimate-Facebook-Scraper#135]
Hi there,
I got this error, as in the subject: NameError: name 'facebook_https_prefix' is not defined

Can you help me?

> C:\Users\x\Downloads\Ultimate-Facebook-Scraper-2.0\Ultimate-Facebook-Scraper-2.0>ultimate-facebook-scraper
> Traceback (most recent call last):
>   File "C:\Users\x\AppData\Local\Programs\Python\Python38\Scripts\ultimate-facebook-scraper-script.py", line 11, in <module>
>     load_entry_point('ultimate-facebook-scraper', 'console_scripts', 'ultimate-facebook-scraper')()
>   File "c:\users\x\appdata\local\programs\python\python38\lib\site-packages\pkg_resources\__init__.py", line 489, in load_entry_point
>     return get_distribution(dist).load_entry_point(group, name)
>   File "c:\users\x\appdata\local\programs\python\python38\lib\site-packages\pkg_resources\__init__.py", line 2852, in load_entry_point
>     return ep.load()
>   File "c:\users\x\appdata\local\programs\python\python38\lib\site-packages\pkg_resources\__init__.py", line 2443, in load
>     return self.resolve()
>   File "c:\users\x\appdata\local\programs\python\python38\lib\site-packages\pkg_resources\__init__.py", line 2449, in resolve
>     module = __import__(self.module_name, fromlist=['__name__'], level=0)
>   File "c:\users\x\downloads\ultimate-facebook-scraper-2.0\ultimate-facebook-scraper-2.0\scraper\__main__.py", line 3, in <module>
>     scraper()
>   File "c:\users\x\downloads\ultimate-facebook-scraper-2.0\ultimate-facebook-scraper-2.0\scraper\scraper.py", line 797, in scraper
>     urls = [
>   File "c:\users\x\downloads\ultimate-facebook-scraper-2.0\ultimate-facebook-scraper-2.0\scraper\scraper.py", line 798, in <listcomp>
>     facebook_https_prefix + facebook_link_body + get_item_id(line)
> NameError: name 'facebook_https_prefix' is not defined

**Comment by Iwazo8700** [comment]
I have the same issue

**Comment by aymather** [comment]
@harismuneer I also have the same issue, any solutions?

**Comment by papaya-ais** [comment]
run collection/crawler.py
not __main__.py
