### ISSUE TITLE
Posts.txt is empty

### ISSUE THREAD

**Issue by sunnyhasija** [harismuneer/Ultimate-Facebook-Scraper#137]
**Describe the bug**
The Posts.txt file only has the column headers, not posts in it after scraping a group page. 

**To Reproduce**
scrape any group.

**Expected behavior**
Posts.txt has posts and comments. 

**Additional context**
I think it could be because the xpath variable have changed. They might need to be updated.

**Comment by Jib128** [comment]
Second this. All of the files in the "data" folder are blank.

**Comment by sunnyhasija** [comment]
I have been able to fix some of the issues. 

I changed one of the selectors for the posts - and it seems to work. 

Moreover, @Jib128 make sure you are on the old facebook, and not the new one that they are rolling out. You can switch to classic facebook via the method described in [this link. ](https://www.facebook.com/help/645404059595478)

**Comment by Jib128** [comment]
> I have been able to fix some of the issues.
> 
> I changed one of the selectors for the posts - and it seems to work.
> 
> Moreover, @Jib128 make sure you are on the old facebook, and not the new one that they are rolling out. You can switch to classic facebook via the method described in [this link. ](https://www.facebook.com/help/645404059595478)

I switched over to the old facebook and it worked! I'm guessing the script wasn't updated for the new API.

**Comment by MACHDesignLabs** [comment]
Looks like Facebook is making it difficult to revert to old view by not providing users with the link. @sunnyhasija do you have a branch with those fixes?
