### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'selectors.json'"** 

### ISSUE THREAD

**Issue by bandsk** [harismuneer/Ultimate-Facebook-Scraper#141]
I am running this on Mac in Terminal (Python 3.8) and am receiving the error: 

**"lewien@Es-MacBook-Pro ~ % python /Users/lewien/Ultimate-Facebook-Scraper/scraper/scraper.py 
{'uploaded_photos': True, 'friends_photos': True, 'friends_small_size': True, 'photos_small_size': True, 'total_scrolls': 2500, 'scroll_time': 8}
Traceback (most recent call last):
  File "/Users/lewien/Ultimate-Facebook-Scraper/scraper/scraper.py", line 893, in <module>
    with open("selectors.json") as a, open("params.json") as b:
FileNotFoundError: [Errno 2] No such file or directory: 'selectors.json'"** 

Another individual had this problem, but a solution is not posted: 
https://github.com/harismuneer/Ultimate-Facebook-Scraper/issues/97 

Any ideas how to fix this? Thanks!

**Comment by Rahulsunny11** [comment]
HI @bandsk I am having the same issue.. did you resolve it?

**Comment by bandsk** [comment]
Unfortunately no. I gave up and started working from another angle. Good
luck!

**Comment by Rahulsunny11** [comment]
@bandsk oh.. did you find any other script to scrape? if yes. please share it with me too

**Comment by omonimus1** [comment]
@bandsk The file has been moved in the root folder (same with input.txt and credentials.yaml ). It was enough to modify the absolute path of these files in the scraper.py
'../selectors.json'

**Comment by rf-redux** [comment]
Am having this issue as well. Sigh.

**Comment by harismuneer** [comment]
### 📢 Important Announcement: UFS 2.0 (with support for latest Facebook UI)

Hi guys! The exclusive version of **UFS 2.0** supports scraping for the latest Facebook UI along with many powerful features, much better organization through CSV (Excel-like) file format, bug fixes, and multiple browser support. You can get exclusive access here: 

#### **[Buy UFS 2.0](https://tinyurl.com/UFS-NEW)** 

Building the new version has been a tough technical challenge and I have spent a considerable amount of time and effort on building it. Therefore, kindly support by purchasing it from the link shared [above.](https://tinyurl.com/UFS-NEW) 

<hr>
You can also share small donations through these links:


- <a href="https://buy.paddle.com/product/638653"><b>Platinum (99.99$)</b> -> 2 hours of development<a/>
- <a href="https://buy.paddle.com/product/638651"><b>Gold (49.99$)</b> -> 1 hour of development</a>
- <a href="https://buy.paddle.com/product/638654"><b>Silver (19.99$)</b> -> 30 minutes of development</a>

_If **considerable support is shown through the above donations then I will release the version for the general public** after some time as I want to keep this software open-sourced. So, now is the time for all those folks who benefited from the tool to support its reach for a wider audience :)_
