### ISSUE TITLE
Scrape Photos from "/Photos"

### ISSUE THREAD

**Issue by Jib128** [harismuneer/Ultimate-Facebook-Scraper#142]
I noticed that when I used the scraper on the target profile, I only got twenty pictures or so from the "uploaded photos". Is there a way to download all pictures from their profile? 

For example, if I go to https://www.facebook.com/zuck/photos I want to be able to download all photos from this page?

**Comment by Unixware** [comment]
snake-oil program... for me just dloads some text data not even a pic,  yes I am on the "classic" and no 2FA
