### ISSUE TITLE
The data does not contain the user's picture.

### ISSUE THREAD

**Issue by D0641651** [harismuneer/Ultimate-Facebook-Scraper#148]
Sorry my english is not good.

**Describe the bug**
https://imgur.com/a/QRns1F2
The data does not contain the user's picture.

https://imgur.com/tMG6QrZ
In Posts.txt, some POST_ID is wrong and LINK is empty.

**To Reproduce**
1. Configure '…'
2. Run 'python scraper/scraper.py --uploaded_photos True --friends_photos False --photos_small_size False'
3. …

**Expected behavior**
I want to download pictures uploaded by users.

**Screenshots or command output**
```
Scraping: https://www.facebook.com/bambinuna
----------------------------------------
Scraping Friends..
Friends Done!
----------------------------------------
Scraping Photos..
Photos Done!
----------------------------------------
Scraping Videos..
Exception (scrape_data) 0 Status = 2 <class 'selenium.common.exceptions.NoSuchElementException'>
Exception (scrape_data) 1 Status = 2 <class 'selenium.common.exceptions.NoSuchElementException'>
Videos Done!
----------------------------------------
Scraping About..
About Done!
----------------------------------------
Scraping Posts..
Posts Done!
Finished Scraping Profile https://www.facebook.com/bambinuna.
```
**Desktop (please complete the following information):**
 - OS: [Win 10]
 - Python version [3.7.5]
 - Chrome web driver version [84.0.4147]

**Additional context**

**Comment by harismuneer** [comment]
### 📢 Important Announcement: UFS 2.0 (with support for latest Facebook UI)

Hi guys! The exclusive version of **UFS 2.0** supports scraping for the latest Facebook UI along with many powerful features, much better organization through CSV (Excel-like) file format, bug fixes, and multiple browser support. You can get exclusive access here: 

#### **[Buy UFS 2.0](https://tinyurl.com/UFS-NEW)** 

Building the new version has been a tough technical challenge and I have spent a considerable amount of time and effort on building it. Therefore, kindly support by purchasing it from the link shared [above.](https://tinyurl.com/UFS-NEW) 

<hr>
You can also share small donations through these links:


- <a href="https://buy.paddle.com/product/638653"><b>Platinum (99.99$)</b> -> 2 hours of development<a/>
- <a href="https://buy.paddle.com/product/638651"><b>Gold (49.99$)</b> -> 1 hour of development</a>
- <a href="https://buy.paddle.com/product/638654"><b>Silver (19.99$)</b> -> 30 minutes of development</a>

_If **considerable support is shown through the above donations then I will release the version for the general public** after some time as I want to keep this software open-sourced. So, now is the time for all those folks who benefited from the tool to support its reach for a wider audience :)_
