### ISSUE TITLE
Chrome stops after having scrolled down 75% and doesn't collect the rest of the timeline as well as photos. same happens with friends: only gets 800friends when there are actually 1-3 thousand. also doesn't collect tagged photos anymore.

### ISSUE THREAD

**Issue by github-userx** [harismuneer/Ultimate-Facebook-Scraper#15]

**Comment by harismuneer** [comment]
@github-userx, if the friends list is quite large and there are a lot of timeline posts then you can try changing the 'total_scrolls' variable to a larger value like 10000 or maybe more depending on your needs. 

Also, as far as the tagged photos are concerned, I just ran the tool and it worked like a charm. It scraped all the uploaded photos as well as the tagged photos. Also, if the tagged photos of the person whose profile you are scraping aren't visible to you, then the scraper won't scrape them.

Some of the Graph URL don't work now. I am using the ones that work. Also, I am glad that you are putting effort into exploring this stuff. Maybe you can add more features to UFS and generate a pull request :)
