### ISSUE TITLE
Text from last post is repeated in all posts

### ISSUE THREAD

**Issue by flowsta** [harismuneer/Ultimate-Facebook-Scraper#152]
**Describe the bug**
The text of the last post is repeated in every post scraped

**To Reproduce**

This is what I do:
```
python3 scraper/scraper.py --uploaded_photos True --friends_photos True --friends_small_size True --photos_small_size True --total_scrolls 2500 --scroll_time 8
```

**Expected behavior**
In .data/user/Posts.txt I expected to get the text of every post published

**Screenshots or command output**
This is the structure of Posts.txt:
(When you say TITLE you mean the text of the POST?)
```
 TIME || TYPE  || TITLE || STATUS  ||   LINKS(Shared Posts/Shared Links etc) || POST_ID 

Right Date time || others || Johnny Doe in John Doe || Last post's title  ||  || post id
Right Date time || others || Joe Doe in John Doe || Last post's title ||  || othe post id
Right Date time || status update || John Doe || Last post's title || URL of the post || 0
Right Date time || status update || John Doe || Last post's title || URL of the post published from Instagram || post id
```
**Desktop (please complete the following information):**
 - OS: Debian GNU/Linux
 - Python version: Python 3.8.5
 - Chrome web driver version: 84

**Additional context**
First time I run it Posts.txt was empty but I found the issue where you explained to go back to the old shape.

**Comment by kentebird** [comment]
I have also encountered this issue

**Comment by AskGuan** [comment]
I saw the problem.
There is a path error in the file "selectors.json"
"status": ".//div[contains(@class, '_5pbx')]",  #Notice the first point
 "status_exc": ".//div[@class='userContent']",

**Comment by nicoayci** [comment]
> "status": ".//div[contains(@Class, '_5pbx')]", #Notice the first point
> "status_exc": ".//div[@Class='userContent']",

did not work for me :(

**Comment by papaya-ais** [comment]
> I saw the problem.
> There is a path error in the file "selectors.json"
> "status": ".//div[contains(@Class, '_5pbx')]", #Notice the first point
> "status_exc": ".//div[@Class='userContent']",

didn't work for me too...

**Comment by AskGuan** [comment]
facebook has changed to an new UI, the old "selectors.json" doesn't work
you can switch to #176 to change the UI to old UI, And then you can continue to use it
It was still in effect until now

**Comment by papaya-ais** [comment]
> facebook has changed to an new UI, the old "selectors.json" doesn't work
> you can switch to #176 to change the UI to old UI, And then you can continue to use it
> It was still in effect until now

Thank you but I'm already using old UI ('-`)

**Comment by AskGuan** [comment]
maybe you could exchange the content between status and status_exc
but i don't think this is the key

**Comment by papaya-ais** [comment]
> maybe you could exchange the content between status and status_exc
> but i don't think this is the key

THAT WAS THE KEY I SOLVED THIS I SOLVED THIS
Thank you very thank you AskGuan. I changed status to status_exc and now it works well ! ! ! YEAH~~!!!!

**Comment by DanielBuzkov** [comment]
I have the same problem...
I switched to old agent for the UI and switched the status_exc with status, but I still get `<class 'selenium.common.exceptions.NoSuchElementException'>` while scraping, and I get `<class 'IndexError'>` in the `about` scrape
Any help?

**Comment by papaya-ais** [comment]
In my case, I didn't get any exception but contents I got were strange. I think that you are not same case with mine.
I recommend you test your old agent appropriate. If your old agent shows mobile version of facebook, then it can be occur NoSuchElementException.

**Comment by AskGuan** [comment]
If that user's about is empty or private, this is true, and the same could be occur for "friends" scrape

**Comment by DanielBuzkov** [comment]
I've used the old Nokia agent which someone suggested here somewhere not a while ago, and the `Mozilla/5.0 (Windows NT 6.3; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0` agent.
Which agent have you used for it to work?

**Comment by DanielBuzkov** [comment]
Oh sorry I mixed up the issues, it really is a different issue but #176 had the same problem as me

**Comment by papaya-ais** [comment]
![image](https://user-images.githubusercontent.com/71307736/95963913-3897c400-0e43-11eb-9c44-599493626350.png)

That agent shows mobile facebook.. It will not work for you
Oh, did you saw #176 and used that agent?
I think that facebook is monitoring this. About 4 hour after I comment that, it suddenly changed to mobile facebook not just old web facebook.
I recommend you that test many user-agents for using this crawler...

**Comment by DanielBuzkov** [comment]
Oh that's cool honestly
Thank you I'll give it a try
I have several agents to try :)

**Comment by harismuneer** [comment]
### 📢 Important Announcement: UFS 2.0 (with support for latest Facebook UI)

Hi guys! The exclusive version of **UFS 2.0** supports scraping for the latest Facebook UI along with many powerful features, much better organization through CSV (Excel-like) file format, bug fixes, and multiple browser support. You can get exclusive access here: 

#### **[Buy UFS 2.0](https://tinyurl.com/UFS-NEW)** 

Building the new version has been a tough technical challenge and I have spent a considerable amount of time and effort on building it. Therefore, kindly support by purchasing it from the link shared [above.](https://tinyurl.com/UFS-NEW) 

<hr>
You can also share small donations through these links:


- <a href="https://buy.paddle.com/product/638653"><b>Platinum (99.99$)</b> -> 2 hours of development<a/>
- <a href="https://buy.paddle.com/product/638651"><b>Gold (49.99$)</b> -> 1 hour of development</a>
- <a href="https://buy.paddle.com/product/638654"><b>Silver (19.99$)</b> -> 30 minutes of development</a>

_If **considerable support is shown through the above donations then I will release the version for the general public** after some time as I want to keep this software open-sourced. So, now is the time for all those folks who benefited from the tool to support its reach for a wider audience :)_
