### ISSUE TITLE
Groups not being Scraped

### ISSUE THREAD

**Issue by mikebardpython** [harismuneer/Ultimate-Facebook-Scraper#153]
**Describe the bug**

**To Reproduce**
1. Configure '…'
2. Run '…'
3. …

**Expected behavior**

**Screenshots or command output**
If applicable, add screenshots or `output logs` to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Linux]
 - Python version [e.g. 3.7.5]
 - Chrome web driver version [e.g 81]

**Additional context**

**Comment by mikebardpython** [comment]
Describe the bug
url for groups is dropping the word groups
example:
https://www.facebook.com/groups/5daytaxresolutionchallenge

turns into
https://www.facebook.com/5daytaxresolutionchallenge

As a result no results are scraped.

Desktop (please complete the following information):

OS: Windows10
Python version 3.7.1
Chrome web driver version 84.0.4147
Additional context
Add any other context about the problem here.

**Comment by sunnyhasija** [comment]
Bump. Its happening to me too.

**Comment by rorysmith85** [comment]
Same thing is happening to me as well.

**Comment by purpl3horse** [comment]
Here as well. Bump.

**Comment by rytmisk** [comment]
For me it works but only if I have Facebook set to classic look in Chrome.

**Comment by purpl3horse** [comment]
> For me it works but only if I have Facebook set to classic look in Chrome.

Classic look will be removed in 7 days

**Comment by Omarmarei** [comment]
Using group id instead of name in url fixed this for me ex: fb.com/12912321031 instead of fb.com/groups/groupname

**Comment by harismuneer** [comment]
### 📢 Important Announcement: UFS 2.0 (with support for latest Facebook UI)

Hi guys! The exclusive version of **UFS 2.0** supports scraping for the latest Facebook UI along with many powerful features, much better organization through CSV (Excel-like) file format, bug fixes, and multiple browser support. You can get exclusive access here: 

#### **[Buy UFS 2.0](https://tinyurl.com/UFS-NEW)** 

Building the new version has been a tough technical challenge and I have spent a considerable amount of time and effort on building it. Therefore, kindly support by purchasing it from the link shared [above.](https://tinyurl.com/UFS-NEW) 

<hr>
You can also share small donations through these links:


- <a href="https://buy.paddle.com/product/638653"><b>Platinum (99.99$)</b> -> 2 hours of development<a/>
- <a href="https://buy.paddle.com/product/638651"><b>Gold (49.99$)</b> -> 1 hour of development</a>
- <a href="https://buy.paddle.com/product/638654"><b>Silver (19.99$)</b> -> 30 minutes of development</a>

_If **considerable support is shown through the above donations then I will release the version for the general public** after some time as I want to keep this software open-sourced. So, now is the time for all those folks who benefited from the tool to support its reach for a wider audience :)_

**Comment by sunnyhasija** [comment]
You know this does not help academics at all. $400 for the software is very steep. 

Unless this was running all sorts of advanced analytics on the data, that much money for a scraper just comes across as a money grab. I would happily give citations to this software in my work, but paying that much seems wrong.

**Comment by harismuneer** [comment]
Hi, thank you for the message. The cost is somewhat around 240ish. I had another product with that template so some issue in plugging that in; updated the link. Also, its not about the cost per say, its about the spirit that people should donate to keep open-source software alive. I have been maintaining this tool for many years now without any single donation. Since I code such tools for the benefit of the wider community.

Anyways, feel free to donate whatever you can so together we can open-source the latest version for the general public. It has some great revamp around the whole code along with many stable bug fixes and some great new features. Thanks and good luck with your research, certainly a citation will give great exposure to our tool 👍
