### ISSUE TITLE
Question: Which argument should I change to download all the photos uploaded?

### ISSUE THREAD

**Issue by punisher44** [harismuneer/Ultimate-Facebook-Scraper#154]
Hi,
I'm not facing any errors, but I have one question to ask. When I run the scraper, it's only able to download only about 12 photos uploaded by my target user. Which argument should I change in the code to download all the photos uploaded? 
(I'm assuming it to either be 'total_scrolls' or 'scroll_time.')
(btw I changed the default value of 'total_scrolls' from 2500 to 10000, cause I felt this is the one which I should change.)

![arguments](https://user-images.githubusercontent.com/69133975/89149558-67660400-d58f-11ea-8492-83d89382f096.png)

Thank you.

**Comment by harismuneer** [comment]
Hi, You have to increase the `total_scrolls` value to fetch more data but I see even with 2500 scollls, 12 photos are very less.

There might be a potential bug in the code due to which its not scraping that much data (only if the data really exists).

I have developed a new version with major improvements. You can check that out below.

**Comment by harismuneer** [comment]
### 📢 Important Announcement: UFS 2.0 (with support for latest Facebook UI)

Hi guys! The exclusive version of **UFS 2.0** supports scraping for the latest Facebook UI along with many powerful features, much better organization through CSV (Excel-like) file format, bug fixes, and multiple browser support. You can get exclusive access here: 

#### **[Buy UFS 2.0](https://tinyurl.com/UFS-NEW)** 

Building the new version has been a tough technical challenge and I have spent a considerable amount of time and effort on building it. Therefore, kindly support by purchasing it from the link shared [above.](https://tinyurl.com/UFS-NEW) 

<hr>
You can also share small donations through these links:


- <a href="https://buy.paddle.com/product/638653"><b>Platinum (99.99$)</b> -> 2 hours of development<a/>
- <a href="https://buy.paddle.com/product/638651"><b>Gold (49.99$)</b> -> 1 hour of development</a>
- <a href="https://buy.paddle.com/product/638654"><b>Silver (19.99$)</b> -> 30 minutes of development</a>

_If **considerable support is shown through the above donations then I will release the version for the general public** after some time as I want to keep this software open-sourced. So, now is the time for all those folks who benefited from the tool to support its reach for a wider audience :)_
