### ISSUE TITLE
Make it work Without browser integration

### ISSUE THREAD

**Issue by nasirxo** [harismuneer/Ultimate-Facebook-Scraper#155]
See my library for fb scrapping
$pip insall nshack

It works without any browser integration
And is much more faster than UFS and have minimal dependencies also have bots to reply to inbox and comment's and a maths bot that replies to maths questions

DEVELOPER
fb.com/nasir.xo
github.com/nasirxo

**Comment by harismuneer** [comment]
![image](https://user-images.githubusercontent.com/30947706/91322653-6f554480-e7d9-11ea-8f23-1ba30aad6c27.png)

@nasirxo Man, I didn't expect this from you. Grow up and raise your moral standards.
