### ISSUE TITLE
cant login  - running  in docker container

### ISSUE THREAD

**Issue by ksahmed** [harismuneer/Ultimate-Facebook-Scraper#158]
**Describe the bug**
a build a container with all dependencies including chrome and when i run, i get the error on login

**To Reproduce**
1. Configure '…' ( use default settings) **but add headless option in login method** 
2. Run '…'
3. …

**Expected behavior**
login and scraping 

**Screenshots or command output**
PS C:\Projects\Ultimate-Facebook-Scraper> docker run --name crawler3 crawler3                                           [WDM] - Current google-chrome version is 84.0.4147
[WDM] - Get LATEST driver version for 84.0.4147
[WDM] - There is no [linux64] chromedriver for browser 84.0.4147 in cache
[WDM] - Get LATEST driver version for 84.0.4147
[WDM] - Trying to download new driver from http://chromedriver.storage.googleapis.com/84.0.4147.30/chromedriver_linux64.zip
[WDM] - Driver has been saved in cache [/root/.wdm/drivers/chromedriver/linux64/84.0.4147.30]
{'uploaded_photos': True, 'friends_photos': True, 'friends_small_size': True, 'photos_small_size': True, 'total_scrolls': 2500, 'scroll_time': 8}

Starting Scraping...

There's some error in log in.
<class 'TypeError'>

**Desktop (please complete the following information):**
 - OS: [e.g. windows with linux docker]
 - Python version [e.g. 3.7.8]
 - Chrome web driver version [e.g 84]

**Additional context**

**Comment by AlaaHamoudah** [comment]
I face the same issue, any solution here?

**Comment by harismuneer** [comment]
### 📢 Important Announcement: UFS 2.0 (with support for latest Facebook UI)

Hi guys! The exclusive version of **UFS 2.0** supports scraping for the latest Facebook UI along with many powerful features, much better organization through CSV (Excel-like) file format, bug fixes, and multiple browser support. You can get exclusive access here: 

#### **[Buy UFS 2.0](https://tinyurl.com/UFS-NEW)** 

Building the new version has been a tough technical challenge and I have spent a considerable amount of time and effort on building it. Therefore, kindly support by purchasing it from the link shared [above.](https://tinyurl.com/UFS-NEW) 

<hr>
You can also share small donations through these links:


- <a href="https://buy.paddle.com/product/638653"><b>Platinum (99.99$)</b> -> 2 hours of development<a/>
- <a href="https://buy.paddle.com/product/638651"><b>Gold (49.99$)</b> -> 1 hour of development</a>
- <a href="https://buy.paddle.com/product/638654"><b>Silver (19.99$)</b> -> 30 minutes of development</a>

_If **considerable support is shown through the above donations then I will release the version for the general public** after some time as I want to keep this software open-sourced. So, now is the time for all those folks who benefited from the tool to support its reach for a wider audience :)_
