### ISSUE TITLE
I run the code successfully but got plain text files. 

### ISSUE THREAD

**Issue by expmphp** [harismuneer/Ultimate-Facebook-Scraper#161]
**Describe the bug**
I run the code successfully but got plain text files. 

**Screenshots or command output**

Starting Scraping...
 
[WDM] - Current google-chrome version is 85.0.4183
[WDM] - Get LATEST driver version for 85.0.4183
[WDM] - Driver [/Users/expmphp/.wdm/drivers/chromedriver/mac64/85.0.4183.87/chromedriver] found in cache

Scraping: https://www.facebook.com/warnerbrosent
----------------------------------------
Scraping Friends..
Exception (scrape_data) 0 Status = 0 <class 'selenium.common.exceptions.NoSuchElementException'>
Exception (scrape_data) 1 Status = 0 <class 'selenium.common.exceptions.NoSuchElementException'>
Exception (scrape_data) 2 Status = 0 <class 'selenium.common.exceptions.NoSuchElementException'>
Exception (scrape_data) 3 Status = 0 <class 'selenium.common.exceptions.NoSuchElementException'>
Exception (scrape_data) 4 Status = 0 <class 'selenium.common.exceptions.NoSuchElementException'>
Exception (scrape_data) 5 Status = 0 <class 'selenium.common.exceptions.NoSuchElementException'>
Exception (scrape_data) 6 Status = 0 <class 'selenium.common.exceptions.NoSuchElementException'>
Exception (scrape_data) 7 Status = 0 <class 'selenium.common.exceptions.NoSuchElementException'>
Friends Done!
----------------------------------------
Scraping Photos..
Exception (scrape_data) 0 Status = 1 <class 'selenium.common.exceptions.NoSuchElementException'>
Exception (scrape_data) 1 Status = 1 <class 'selenium.common.exceptions.NoSuchElementException'>
Photos Done!
----------------------------------------
Scraping Videos..
Exception (scrape_data) 0 Status = 2 <class 'selenium.common.exceptions.NoSuchElementException'>
Exception (scrape_data) 1 Status = 2 <class 'selenium.common.exceptions.NoSuchElementException'>
Videos Done!
----------------------------------------
Scraping About..
Exception (save_to_file) Status = 3 <class 'IndexError'>
Exception (save_to_file) Status = 3 <class 'IndexError'>
Exception (save_to_file) Status = 3 <class 'IndexError'>
Exception (save_to_file) Status = 3 <class 'IndexError'>
Exception (save_to_file) Status = 3 <class 'IndexError'>
Exception (save_to_file) Status = 3 <class 'IndexError'>
Exception (save_to_file) Status = 3 <class 'IndexError'>
About Done!
----------------------------------------
Scraping Posts..
Posts Done!
Finished Scraping Profile https://www.facebook.com/warnerbrosent.

**Desktop (please complete the following information):**
 - Python version 3.7.3
 - Chrome web driver version : The latest one, just reinstalled.

Could you please tell me what’s wrong? Thank you.

**Comment by Billybob2221** [comment]
Same issues here !

**Comment by m-mohiey** [comment]
I got the same situation also.

**Comment by Enkh99** [comment]
Make sure you installed "pip install -e ." correctly. Note that it has dot at the end. Your facebook version must ve set on classic old version. Better choose user that you scraping is public for everyone.

**Comment by Enkh99** [comment]
Facebook language should be English. And also check that issue and follow the instruct. https://github.com/harismuneer/Ultimate-Facebook-Scraper/commit/d3eabce9b06e82e90acb65f19a8a58400b632c30

**Comment by expmphp** [comment]
Thank you. 
I switch the facebook version to old version  and it is English, but it still doesn't work. And I am sure I put  "pip install -e ." correctly.  The page is a public page : Warner Bros. Entertainment.
I got many files 'Contact and Basic Info', 'Details About', 'Family and Relationships' but no content inside.
Not sure what's wrong.

**Comment by AlaaHamoudah** [comment]
It's about the html selectors, FB keeps changing them regularly. The exception that u have `selenium.common.exceptions.NoSuchElementException` means the selector is not there. You need to update it. I am facing the same issue. If I fix it, will let u know

**Comment by AlaaHamoudah** [comment]
So it works for me by switching [old Facebook design](https://gadgetstouse.com/blog/2020/06/08/switch-back-to-old-facebook-design/).

**Comment by Enkh99** [comment]
> Thank you.
> I switch the facebook version to old version and it is English, but it still doesn't work. And I am sure I put "pip install -e ." correctly. The page is a public page : Warner Bros. Entertainment.
> I got many files 'Contact and Basic Info', 'Details About', 'Family and Relationships' but no content inside.
> Not sure what's wrong.

**Comment by expmphp** [comment]
Hi, I switched it to the old version, but it still doesn't work.

**Comment by papaya-ais** [comment]
> So it works for me by switching [old Facebook design](https://gadgetstouse.com/blog/2020/06/08/switch-back-to-old-facebook-design/).

Thx it works for me too I love u

**Comment by luismiguells** [comment]
Same issue here. Right now can't switch to the old version of Facebook.

**Comment by emalov98ffm** [comment]
This thing not working for months now...

**Comment by papaya-ais** [comment]
Maybe this will help u
https://github.com/kevinzg/facebook-scraper
It works now

**Comment by emalov98ffm** [comment]
> Maybe this will help u
> https://github.com/kevinzg/facebook-scraper
> It works now

Only but Pages

**Comment by papaya-ais** [comment]
Need image or video also? or comments?

image or video -> you can get url of image and video, use that
comments -> you can get url of page, go mobile page and scrape comments with selenium and bs4.

**Comment by emalov98ffm** [comment]
> Need image or video also? or comments?
> 
> image or video -> you can get url of image and video, use that
> comments -> you can get url of page, go mobile page and scrape comments with selenium and bs4.

Images only

**Comment by emalov98ffm** [comment]
For Profiles, not Pages

**Comment by papaya-ais** [comment]
Then you have to make your own facebook profile crawler. I searched many facebook crawler but none of them crawed profile data without Ultimate-Facebook-Scraper - that doesn't work now

**Comment by harismuneer** [comment]
### 📢 Important Announcement: UFS 2.0 (with support for latest Facebook UI)

Hi guys! The exclusive version of **UFS 2.0** supports scraping for the latest Facebook UI along with many powerful features, much better organization through CSV (Excel-like) file format, bug fixes, and multiple browser support. You can get exclusive access here: 

#### **[Buy UFS 2.0](https://tinyurl.com/UFS-NEW)** 

Building the new version has been a tough technical challenge and I have spent a considerable amount of time and effort on building it. Therefore, kindly support by purchasing it from the link shared [above.](https://tinyurl.com/UFS-NEW) 

<hr>
You can also share small donations through these links:


- <a href="https://buy.paddle.com/product/638653"><b>Platinum (99.99$)</b> -> 2 hours of development<a/>
- <a href="https://buy.paddle.com/product/638651"><b>Gold (49.99$)</b> -> 1 hour of development</a>
- <a href="https://buy.paddle.com/product/638654"><b>Silver (19.99$)</b> -> 30 minutes of development</a>

_If **considerable support is shown through the above donations then I will release the version for the general public** after some time as I want to keep this software open-sourced. So, now is the time for all those folks who benefited from the tool to support its reach for a wider audience :)_
