### ISSUE TITLE
Output files are empty

### ISSUE THREAD

**Issue by teslab2020** [harismuneer/Ultimate-Facebook-Scraper#167]
Hello,

I ran the scrapper successfully. I checked the output in data folder. Unfortunately, all the text files are empty.
Can anyone help me to understand why the files are empty, please?

Thank you in advance!

**Comment by rytmisk** [comment]
Have you first opened facebook in Chrome and changed to classic view?

**Comment by infominer33** [comment]
Classic is cancelled:

https://mashable.com/article/facebook-classic-look-september/

**Comment by rytmisk** [comment]
It is still possible to switch to classic for 48 hours (just checked). And if you change to another user agent (as per my issue #165) this would be automatic for a long time still.

**Comment by lufffyyyyy** [comment]
Where exactly is that option to switch back to classic view for 48 hours?

**Comment by rytmisk** [comment]
The description in [this link](https://www.facebook.com/help/645404059595478) still works for me

**Comment by l0ophole** [comment]
I changed to classic but the data folder only has a subdirectory for the group id I'm trying to scape, but the subdirectory is empty.

**Comment by l0ophole** [comment]
nevermind. I just didn't wait long enough.

**Comment by luismiguells** [comment]
I have the same problem. Do anyone know how to fix it?

**Comment by rytmisk** [comment]
Have you waited until the script finishes? It can take some hours. It might seem like it is finished since it first browses through the posts before actually trying to scrape them (at least that is how it looks to me - I have not looked at the code)
Ketil

**Comment by luismiguells** [comment]
@rytmisk I let the script finish and I still get the empty files.

**Comment by rytmisk** [comment]
Then I don't know sorry! I fixed this by changing to classic facebook and English language and let the script run for the required time.

**Comment by michalani** [comment]
Facebook has deleted the option to use the old facebook view, meaning this tools will not work.

**Comment by saacs88** [comment]
This chrome addone will let you use classic view:

https://oldlayout.com/

**Comment by harismuneer** [comment]
### 📢 Important Announcement: UFS 2.0 (with support for latest Facebook UI)

Hi guys! The exclusive version of **UFS 2.0** supports scraping for the latest Facebook UI along with many powerful features, much better organization through CSV (Excel-like) file format, bug fixes, and multiple browser support. You can get exclusive access here: 

#### **[Buy UFS 2.0](https://tinyurl.com/UFS-NEW)** 

Building the new version has been a tough technical challenge and I have spent a considerable amount of time and effort on building it. Therefore, kindly support by purchasing it from the link shared [above.](https://tinyurl.com/UFS-NEW) 

<hr>
You can also share small donations through these links:


- <a href="https://buy.paddle.com/product/638653"><b>Platinum (99.99$)</b> -> 2 hours of development<a/>
- <a href="https://buy.paddle.com/product/638651"><b>Gold (49.99$)</b> -> 1 hour of development</a>
- <a href="https://buy.paddle.com/product/638654"><b>Silver (19.99$)</b> -> 30 minutes of development</a>

_If **considerable support is shown through the above donations then I will release the version for the general public** after some time as I want to keep this software open-sourced. So, now is the time for all those folks who benefited from the tool to support its reach for a wider audience :)_
