### ISSUE TITLE
Some error occured in creating the profile directory

### ISSUE THREAD

**Issue by MaxAnders** [harismuneer/Ultimate-Facebook-Scraper#17]
Hi, I have problem with scraper - when I log in to Facebook it showes notification like in the topic. When i put wrong password it has no problem to create profile directory, also creates all txt files but all of them are empty (i assume that is because i have no access to facebook profile without correct pass). Help!

**Comment by awaiskhawaj** [comment]
same issue here

**Comment by depomguss** [comment]
same here

**Comment by harismuneer** [comment]
You have to give your correct Facebook Email and Password to the scraper so that it can login and do scraping. Although its recommended not to use your primary FB account and use some other secondary account.
