### ISSUE TITLE
Update locators for new facebook UI

### ISSUE THREAD

**Issue by jdupuy26** [harismuneer/Ultimate-Facebook-Scraper#176]
Currently, the locators only work with the old FB UI. If the scraper is ran against the new FB UI, selenium fails to find items with `NoSuchElementException`. 

As a workaround one can insert a `pdb.set_trace` before this line https://github.com/harismuneer/Ultimate-Facebook-Scraper/blob/4f54d8473d35b16f81ba5fbff7f112acc35c57bc/scraper/scraper.py#L806

When the debug line is hit, you can go and install this chrome extension https://chrome.google.com/webstore/detail/revert-site/cdnkbhnblhjdjifeibckehifjocllaja?hl=en-US in the selenium-controlled browser and reload the FB page. Then type `continue` to resume the script execution.

Huge thanks for this scraper, very useful!

**Comment by rytmisk** [comment]
Good thinking. 
I still believe a better way would be to code a changed user agent as I propose i #165 . I am not quite sure what is the best user agent to use, but probably a rather old one like Internet explorer 6 or as another script does - an old cell phone user agent. That way UFC will be fairly safe from future recodings from FB

**Comment by papaya-ais** [comment]
> Good thinking.
> I still believe a better way would be to code a changed user agent as I propose i #165 . I am not quite sure what is the best user agent to use, but probably a rather old one like Internet explorer 6 or as another script does - an old cell phone user agent. That way UFC will be fairly safe from future recodings from FB

It saw this and changed my user agent to Mozilla/5.0 (Windows NT 6.3; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0
and that works for me. Thank u and love u

**Comment by papaya-ais** [comment]
https://github.com/harismuneer/Ultimate-Facebook-Scraper/issues/176#issuecomment-704769396
This user-agent doesn't work now.
Test another user-agent that shows old-version web facebook.

**Comment by papaya-ais** [comment]
> 현재 로케이터는 이전 FB UI에서만 작동합니다. 스크레이퍼가 새 FB UI에 대해 실행되면 셀레늄은 `NoSuchElementException`.
> 
> 해결 방법 `pdb.set_trace`으로이 줄 앞에 삽입 할 수 있습니다.
> 
> https://github.com/harismuneer/Ultimate-Facebook-Scraper/blob/4f54d8473d35b16f81ba5fbff7f112acc35c57bc/scraper/scraper.py#L806
> 
> 디버그 라인에 도달하면이 크롬 확장 프로그램 https://chrome.google.com/webstore/detail/revert-site/cdnkbhnblhjdjifeibckehifjocllaja?hl=en-US 를 셀레늄 제어 브라우저에 설치하고 FB를 다시로드 할 수 있습니다. 페이지. 그런 다음 입력 `continue`하여 스크립트 실행을 재개합니다.
> 
> 이 스크레이퍼에 대단히 감사합니다. 매우 유용합니다!

Now all of my old user-agent doesn't shows the old web UI so I tried this and made it
Here's the process

1. go chrome webstore and get link (https://chrome.google.com/webstore/detail/revert-site/cdnkbhnblhjdjifeibckehifjocllaja)
2. put link this site (https://crxextractor.com/) and get crx
3. put crx file to directory that scraper.py locates
4. add chromedriver option
`options.add_extension('extension_2_1_0_0.crx')`

**Comment by easypanda** [comment]
> > Currently, the locators only work with the old FB UI. If the scraper is ran against the new FB UI, selenium fails to find items with `NoSuchElementException`.
> > As a workaround one can insert a `pdb.set_trace` before this line
> > https://github.com/harismuneer/Ultimate-Facebook-Scraper/blob/4f54d8473d35b16f81ba5fbff7f112acc35c57bc/scraper/scraper.py#L806
> > 
> > When the debug line is hit, you can go and install this chrome extension https://chrome.google.com/webstore/detail/revert-site/cdnkbhnblhjdjifeibckehifjocllaja?hl=en-US in the selenium-controlled browser and reload the FB page. Then type `continue` to resume the script execution.
> > Huge thanks for this scraper, very useful!
> 
> Now all of my old user-agent doesn't shows the old web UI so I tried this and made it
> Here's the process
> 
>     1. go chrome webstore and get link (https://chrome.google.com/webstore/detail/revert-site/cdnkbhnblhjdjifeibckehifjocllaja)
> 
>     2. put link at this site (https://crxextractor.com/) and get crx
> 
>     3. put crx file to directory that scraper.py locates
> 
>     4. add chromedriver option
>        `options.add_extension('extension_2_1_0_0.crx')`

It seems that this solution is not working anymore for me as facebook opens directly on mobile mode instead of showing me the old layout. Any workaround for this?

**Comment by papaya-ais** [comment]
No... I think that it is impossible to use this crawler anymore. Wait for the updates.

**Comment by elig0n** [comment]
still waiting?

**Comment by papaya-ais** [comment]
> > Currently, the locators only work with the old FB UI. If the scraper is ran against the new FB UI, selenium fails to find items with `NoSuchElementException`.
> > As a workaround one can insert a `pdb.set_trace` before this line
> > https://github.com/harismuneer/Ultimate-Facebook-Scraper/blob/4f54d8473d35b16f81ba5fbff7f112acc35c57bc/scraper/scraper.py#L806
> > 
> > When the debug line is hit, you can go and install this chrome extension https://chrome.google.com/webstore/detail/revert-site/cdnkbhnblhjdjifeibckehifjocllaja?hl=en-US in the selenium-controlled browser and reload the FB page. Then type `continue` to resume the script execution.
> > Huge thanks for this scraper, very useful!
> 
> Now all of my old user-agent doesn't shows the old web UI so I tried this and made it
> Here's the process
> 
> 1. go chrome webstore and get link (https://chrome.google.com/webstore/detail/revert-site/cdnkbhnblhjdjifeibckehifjocllaja)
> 2. put link at this site (https://crxextractor.com/) and get crx
> 3. put crx file to directory that scraper.py locates
> 4. add chromedriver option
>    `options.add_extension('extension_2_1_0_0.crx')`

Ultimate Facebook Scraper doesn't working still now. But Revert Site(Chrome extension) updated so you can use solution

**Comment by easypanda** [comment]
> > > Currently, the locators only work with the old FB UI. If the scraper is ran against the new FB UI, selenium fails to find items with `NoSuchElementException`.
> > > As a workaround one can insert a `pdb.set_trace` before this line
> > > https://github.com/harismuneer/Ultimate-Facebook-Scraper/blob/4f54d8473d35b16f81ba5fbff7f112acc35c57bc/scraper/scraper.py#L806
> > > 
> > > When the debug line is hit, you can go and install this chrome extension https://chrome.google.com/webstore/detail/revert-site/cdnkbhnblhjdjifeibckehifjocllaja?hl=en-US in the selenium-controlled browser and reload the FB page. Then type `continue` to resume the script execution.
> > > Huge thanks for this scraper, very useful!
> > 
> > 
> > Now all of my old user-agent doesn't shows the old web UI so I tried this and made it
> > Here's the process
> > 
> > 1. go chrome webstore and get link (https://chrome.google.com/webstore/detail/revert-site/cdnkbhnblhjdjifeibckehifjocllaja)
> > 2. put link at this site (https://crxextractor.com/) and get crx
> > 3. put crx file to directory that scraper.py locates
> > 4. add chromedriver option
> >    `options.add_extension('extension_2_1_0_0.crx')`
> 
> Ultimate Facebook Scraper doesn't working still now. But Revert Site(Chrome extension) updated so you can use solution

This solution doesn't work for me, each time I tried the revert site, it keeps switching to the mobile version and hence it is not able to download the data.

**Comment by papaya-ais** [comment]
Maybe we can use https://github.com/kevinzg/facebook-scraper instead. It uses mobile version facebook UI so it works now.
But it only scrapes text so if you wanna get image of it, then you have to work additionally.

**Comment by harismuneer** [comment]
### 📢 Important Announcement: UFS 2.0 (with support for latest Facebook UI)

Hi guys! The exclusive version of **UFS 2.0** supports scraping for the latest Facebook UI along with many powerful features, much better organization through CSV (Excel-like) file format, bug fixes, and multiple browser support. You can get exclusive access here: 

#### **[Buy UFS 2.0](https://tinyurl.com/UFS-NEW)** 

Building the new version has been a tough technical challenge and I have spent a considerable amount of time and effort on building it. Therefore, kindly support by purchasing it from the link shared [above.](https://tinyurl.com/UFS-NEW) 

<hr>
You can also share small donations through these links:


- <a href="https://buy.paddle.com/product/638653"><b>Platinum (99.99$)</b> -> 2 hours of development<a/>
- <a href="https://buy.paddle.com/product/638651"><b>Gold (49.99$)</b> -> 1 hour of development</a>
- <a href="https://buy.paddle.com/product/638654"><b>Silver (19.99$)</b> -> 30 minutes of development</a>

_If **considerable support is shown through the above donations then I will release the version for the general public** after some time as I want to keep this software open-sourced. So, now is the time for all those folks who benefited from the tool to support its reach for a wider audience :)_

**Comment by harismuneer** [comment]
Also I love how you amazing people tried to find some creative way around to the new UI problem. Keep supporting the open-soruce work :)
