### ISSUE TITLE
selenium.common.exceptions.ElementClickInterceptedException

### ISSUE THREAD

**Issue by gon99martin** [harismuneer/Ultimate-Facebook-Scraper#178]
**Describe the bug**
I'm just trying to test the scraper but I get an error while logging in: selenium.common.exceptions.ElementClickInterceptedException.
I suppose maybe this occurs because the opened Chrome window with Facebook shows a "div" about the acceptance of cookies after the login info has been introduced in the labels, so maybe the scraper tries to find the button «Log In», but it cannot find it due to the fact that now there's this new "div" containing two new buttons: «Manage Data Settings» and «Accept All».
So the solution I have come up with is trying to modify the code so that it presses the «Accept All» button, and after that it can continue with the normal procedure.
How could I achieve this goal? If anyone has any other thought about this error, I'd be very glad to hear about it!

Thank you a lot in advance!

**To Reproduce**
The code I ran on the CLI is:
python scraper/scraper.py \
    --uploaded_photos True \
    --friends_photos False \
    --friends_small_size True \
    --photos_small_size True \
    --total_scrolls 2500 \
    --scroll_time 8

**Expected behavior**
Getting scrapped info.

**Screenshots or command output**
{'uploaded_photos': 'True', 'friends_photos': 'False', 'friends_small_size': 'True', 'photos_small_size': 'True', 'total_scrolls': '2500', 'scroll_time': '8'}

Starting Scraping...
 
[WDM] - Current google-chrome version is 86.0.4240
[WDM] - Get LATEST driver version for 86.0.4240
[WDM] - Driver [/Users/Administrador/.wdm/drivers/chromedriver/mac64/86.0.4240.22/chromedriver] found in cache
There's some error in log in.
<class 'selenium.common.exceptions.ElementClickInterceptedException'>

![image](https://user-images.githubusercontent.com/24585627/95387882-b0b93380-08f1-11eb-9cb6-532f35c83081.png)

**Desktop (please complete the following information):**
 - OS: macOS Catalina Version 10.15.6
 - Python version 3.7.6
 - Chrome web driver version 86.0.4240.22

**Comment by rytmisk** [comment]
Confirm this from two different computers

**Comment by gon99martin** [comment]
@rytmisk I've also tried it on a Windows 10 Pro Version 10.0.18363, running python 3.8.3 and the latest Chrome version, and the result is the same:

![login_f](https://user-images.githubusercontent.com/24585627/95733363-5407a100-0c82-11eb-925c-201d82e82c3e.PNG)
![shell](https://user-images.githubusercontent.com/24585627/95733372-579b2800-0c82-11eb-809c-68ea6f04b507.PNG)

**Comment by AskGuan** [comment]
I have an idea
As a workaround one can insert a pdb.set_trace before this line
`login(cfg["email"], cfg["password"])`
then, it will stop at the login page, you can click it
after that , you can input "continue" to continue the scraper

**Comment by AskGuan** [comment]
> @rytmisk I've also tried it on a Windows 10 Pro Version 10.0.18363, running python 3.8.3 and the latest Chrome version, and the result is the same:
> 
> ![login_f](https://user-images.githubusercontent.com/24585627/95733363-5407a100-0c82-11eb-925c-201d82e82c3e.PNG)
> ![shell](https://user-images.githubusercontent.com/24585627/95733372-579b2800-0c82-11eb-809c-68ea6f04b507.PNG)

I have an idea
As a workaround one can insert a pdb.set_trace before this line
login(cfg["email"], cfg["password"])
then, it will stop at the login page, you can click it
after that , you can input "continue" to continue the scraper

**Comment by gon99martin** [comment]
@rytmisk Your idea works perfectly! The only thing is that the pdb.set_trace() must be inside the function «login», because if it's in the line you said, the same error will occur.
![image](https://user-images.githubusercontent.com/24585627/96106420-84964780-0edb-11eb-82db-ad148083b11e.png)

**Comment by nvanderperren** [comment]
I also have this error. Adding the line `pdb.set_trace()` doesn't solve the issue. If I add that, I get:

```
There's some error in log in.
<class 'NameError'>
```
