### ISSUE TITLE
New UI Returns Empty Results

### ISSUE THREAD

**Issue by alamber2** [harismuneer/Ultimate-Facebook-Scraper#186]
The new FB UI returns empty data files. Is there an update for this coming or a workaround? Changing back to classic UI isn't an option anymore.

**Comment by gonzalo-gongora** [comment]
I am experiencing the same results, I get:
```

Scraping Friends..
Exception (scrape_data) 0 Status = 0 <class 'selenium.common.exceptions.NoSuchElementException'>
Exception (scrape_data) 1 Status = 0 <class 'selenium.common.exceptions.NoSuchElementException'>
Exception (scrape_data) 2 Status = 0 <class 'selenium.common.exceptions.NoSuchElementException'>
Exception (scrape_data) 3 Status = 0 <class 'selenium.common.exceptions.NoSuchElementException'>
Exception (scrape_data) 4 Status = 0 <class 'selenium.common.exceptions.NoSuchElementException'>
Exception (scrape_data) 5 Status = 0 <class 'selenium.common.exceptions.NoSuchElementException'>
Exception (scrape_data) 6 Status = 0 <class 'selenium.common.exceptions.NoSuchElementException'>
Exception (scrape_data) 7 Status = 0 <class 'selenium.common.exceptions.NoSuchElementException'>
Friends Done!
----------------------------------------
Scraping Photos..
Exception (scrape_data) 0 Status = 1 <class 'selenium.common.exceptions.NoSuchElementException'>
Exception (scrape_data) 1 Status = 1 <class 'selenium.common.exceptions.NoSuchElementException'>
Photos Done!
----------------------------------------
Scraping Videos..
Exception (scrape_data) 0 Status = 2 <class 'selenium.common.exceptions.NoSuchElementException'>
Exception (scrape_data) 1 Status = 2 <class 'selenium.common.exceptions.NoSuchElementException'>
Videos Done!
----------------------------------------
Scraping About..
Exception (save_to_file) Status = 3 <class 'IndexError'>
Exception (save_to_file) Status = 3 <class 'IndexError'>
Exception (save_to_file) Status = 3 <class 'IndexError'>
Exception (save_to_file) Status = 3 <class 'IndexError'>
Exception (save_to_file) Status = 3 <class 'IndexError'>
Exception (save_to_file) Status = 3 <class 'IndexError'>
Exception (save_to_file) Status = 3 <class 'IndexError'>
About Done!
----------------------------------------
Scraping Posts..
```
And the output files are empty.

**Comment by alexbrt** [comment]
A quick fix before anyone gets to update the selectors would be to make the driver run the following script right after logging in:
```python
driver.execute_script(
    """
        async function old_layout_switch() {
            let dtsg = null;
            try {
                dtsg = document.body.textContent.match(/"DTSGInitialData".*?"token":"(.*?)"/)[1];
            } catch(e) { }
            try {
                if (!dtsg) {
                    dtsg = document.querySelector('[name="fb_dtsg"]').value
                }
            } catch(e) { }

            let c_user = null;
            try {
                c_user = document.cookie.match(/c_user=([0-9]+)/)[1];
            } catch(e) { }

            let index = 0;
            let urls = [
              `__a=1&dpr=1&__comet_req=1&fb_dtsg=${dtsg}&fb_api_req_friendly_name=CometTrialParticipationChangeMutation&variables={"input":{"change_type":"OPT_OUT","source":"SETTINGS_MENU","actor_id":"${c_user}","client_mutation_id":"1"}}&server_timestamps=true&doc_id=2317726921658975`,
              `__a=1&dpr=1&__comet_req=1&fb_dtsg=${dtsg}&fb_api_req_friendly_name=CometTrialParticipationChangeMutation&variables={"input":{"change_type":"OPT_OUT","source":"FORCED_GROUP_ADMIN_OPT_OUT","actor_id":"${c_user}","client_mutation_id":"4"}}&server_timestamps=true&doc_id=2317726921658975`,
              `__a=1&dpr=1&__comet_req=1&fb_dtsg=${dtsg}&fb_api_req_friendly_name=CometTrialParticipationChangeMutation&variables={"input":{"change_type":"OPT_OUT","source":"FORCED_PAGE_ADMIN_OPT_OUT","actor_id":"${c_user}","client_mutation_id":"2"}}&server_timestamps=true&doc_id=2317726921658975`,
              // Just for fun
              `__a=1&dpr=1&__comet_req=1&fb_dtsg=${dtsg}&fb_api_req_friendly_name=CometTrialParticipationChangeMutation&variables={"input":{"change_type":"OPT_OUT","source":"UNKNOWN","actor_id":"${c_user}","client_mutation_id":"3"}}&server_timestamps=true&doc_id=2317726921658975`
            ];

            let fire = function() {
              const xhr = new XMLHttpRequest();
              xhr.open('POST', 'https://www.facebook.com/api/graphql/');
              xhr.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');
              xhr.setRequestHeader('Referrer', 'https://www.facebook.com/');
              xhr.addEventListener('readystatechange', () => {
                if (xhr.readyState === XMLHttpRequest.DONE) {
                  if (!/"success":true/.test(xhr.responseText)) {
                    if (++index>urls.length) {
                      console.log("Could not switch to old layout.");
                    }
                    else {
                      fire();
                    }
                  } else {
                    location.href = "https://www.facebook.com/?oldlayout=true";
                  }
                }
              });
              xhr.send(urls[index]);
            };
            fire();
        }
        await old_layout_switch();
    """
);
```
All credits go to @matt-kruse for his social media enhancing browser extensions.

Another quick fix would be what @jdupuy26 explained in #176 i.e. pausing the script execution and manually installing the browser extension.

**Comment by HongPhuc89** [comment]
I added your script to the end of login(email, password) function. But it doesn't work

**Comment by djmv** [comment]
> I am experiencing the same results, I get:
> 
> ```
> 
> Scraping Friends..
> Exception (scrape_data) 0 Status = 0 <class 'selenium.common.exceptions.NoSuchElementException'>
> Exception (scrape_data) 1 Status = 0 <class 'selenium.common.exceptions.NoSuchElementException'>
> Exception (scrape_data) 2 Status = 0 <class 'selenium.common.exceptions.NoSuchElementException'>
> Exception (scrape_data) 3 Status = 0 <class 'selenium.common.exceptions.NoSuchElementException'>
> Exception (scrape_data) 4 Status = 0 <class 'selenium.common.exceptions.NoSuchElementException'>
> Exception (scrape_data) 5 Status = 0 <class 'selenium.common.exceptions.NoSuchElementException'>
> Exception (scrape_data) 6 Status = 0 <class 'selenium.common.exceptions.NoSuchElementException'>
> Exception (scrape_data) 7 Status = 0 <class 'selenium.common.exceptions.NoSuchElementException'>
> Friends Done!
> ----------------------------------------
> Scraping Photos..
> Exception (scrape_data) 0 Status = 1 <class 'selenium.common.exceptions.NoSuchElementException'>
> Exception (scrape_data) 1 Status = 1 <class 'selenium.common.exceptions.NoSuchElementException'>
> Photos Done!
> ----------------------------------------
> Scraping Videos..
> Exception (scrape_data) 0 Status = 2 <class 'selenium.common.exceptions.NoSuchElementException'>
> Exception (scrape_data) 1 Status = 2 <class 'selenium.common.exceptions.NoSuchElementException'>
> Videos Done!
> ----------------------------------------
> Scraping About..
> Exception (save_to_file) Status = 3 <class 'IndexError'>
> Exception (save_to_file) Status = 3 <class 'IndexError'>
> Exception (save_to_file) Status = 3 <class 'IndexError'>
> Exception (save_to_file) Status = 3 <class 'IndexError'>
> Exception (save_to_file) Status = 3 <class 'IndexError'>
> Exception (save_to_file) Status = 3 <class 'IndexError'>
> Exception (save_to_file) Status = 3 <class 'IndexError'>
> About Done!
> ----------------------------------------
> Scraping Posts..
> ```
> 
> And the output files are empty.

I got the same errors

**Comment by alexbrt** [comment]
> I added your script to the end of login(email, password) function. But it doesn't work

Try to run the JS in the browser console when logged into facebook. What I did to make it work was to change the `login` function to add the changes made in #185 and added the script above.

**Comment by andi-christ** [comment]
I installed this browser extension which returns FB to the old UI, and the UFS worked. Rad. 

https://oldlayout.com/install.html

**Comment by coffeeboxjoe** [comment]
anyone have any fixes or ideas if you are unable to switch to the UI?

**Comment by elig0n** [comment]
> I added your script to the end of login(email, password) function. But it doesn't work

@alexbrt  @HongPhuc89 I added the snippet right after the call to login() in scraper() before `for url in urls:` and it worked. In the end of login() before the last exception did not work.

**Comment by kalaivendran** [comment]
@elig0n  added like how you add, but didn't work:

       login(cfg["email"], cfg["password"])
        driver.execute_script(
    """
        async function old_layout_switch() {
            let dtsg = null;
            try {
                dtsg = document.body.textContent.match(/"DTSGInitialData".*?"token":"(.*?)"/)[1];
            } catch(e) { }
            try {
                if (!dtsg) {
                    dtsg = document.querySelector('[name="fb_dtsg"]').value
                }
            } catch(e) { }

            let c_user = null;
            try {
                c_user = document.cookie.match(/c_user=([0-9]+)/)[1];
            } catch(e) { }

            let index = 0;
            let urls = [
                `__a=1&dpr=1&__comet_req=1&fb_dtsg=${dtsg}&fb_api_req_friendly_name=CometTrialParticipationChangeMutation&variables={"input":{"change_type":"OPT_OUT","source":"SETTINGS_MENU","actor_id":"${c_user}","client_mutation_id":"1"}}&server_timestamps=true&doc_id=2317726921658975`,
                `__a=1&dpr=1&__comet_req=1&fb_dtsg=${dtsg}&fb_api_req_friendly_name=CometTrialParticipationChangeMutation&variables={"input":{"change_type":"OPT_OUT","source":"FORCED_GROUP_ADMIN_OPT_OUT","actor_id":"${c_user}","client_mutation_id":"4"}}&server_timestamps=true&doc_id=2317726921658975`,
                `__a=1&dpr=1&__comet_req=1&fb_dtsg=${dtsg}&fb_api_req_friendly_name=CometTrialParticipationChangeMutation&variables={"input":{"change_type":"OPT_OUT","source":"FORCED_PAGE_ADMIN_OPT_OUT","actor_id":"${c_user}","client_mutation_id":"2"}}&server_timestamps=true&doc_id=2317726921658975`,
                `__a=1&dpr=1&__comet_req=1&fb_dtsg=${dtsg}&fb_api_req_friendly_name=CometTrialParticipationChangeMutation&variables={"input":{"change_type":"OPT_OUT","source":"UNKNOWN","actor_id":"${c_user}","client_mutation_id":"3"}}&server_timestamps=true&doc_id=2317726921658975`
            ];

            let fire = function() {
                const xhr = new XMLHttpRequest();
                xhr.open('POST', 'https://www.facebook.com/api/graphql/');
                xhr.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');
                xhr.setRequestHeader('Referrer', 'https://www.facebook.com/');
                xhr.addEventListener('readystatechange', () => {
                    if (xhr.readyState === XMLHttpRequest.DONE) {
                        if (!/"success":true/.test(xhr.responseText)) {
                            if (++index>urls.length) {
                                console.log("Could not switch to old layout.");
                            }
                            else {
                                fire();
                            }
                        } else {
                            location.href = "https://www.facebook.com/?oldlayout=true";
                        }
                    }
                });
                xhr.send(urls[index]);
            };
            fire();
        }
        await old_layout_switch();
    """
)

        for url in urls:

**Comment by harismuneer** [comment]
### 📢 Important Announcement: UFS 2.0 (with support for latest Facebook UI)

Hi guys! The exclusive version of **UFS 2.0** supports scraping for the latest Facebook UI along with many powerful features, much better organization through CSV (Excel-like) file format, bug fixes, and multiple browser support. You can get exclusive access here: 

#### **[Buy UFS 2.0](https://tinyurl.com/UFS-NEW)** 

Building the new version has been a tough technical challenge and I have spent a considerable amount of time and effort on building it. Therefore, kindly support by purchasing it from the link shared [above.](https://tinyurl.com/UFS-NEW) 

<hr>
You can also share small donations through these links:


- <a href="https://buy.paddle.com/product/638653"><b>Platinum (99.99$)</b> -> 2 hours of development<a/>
- <a href="https://buy.paddle.com/product/638651"><b>Gold (49.99$)</b> -> 1 hour of development</a>
- <a href="https://buy.paddle.com/product/638654"><b>Silver (19.99$)</b> -> 30 minutes of development</a>

_If **considerable support is shown through the above donations then I will release the version for the general public** after some time as I want to keep this software open-sourced. So, now is the time for all those folks who benefited from the tool to support its reach for a wider audience :)_

**Comment by matt-kruse** [comment]
I've been following along with this since I was tagged. I'm very interested in your approach to scraping, since I am also working on the same for my Social Fixer browser extension. My main focus is the news feed, to filter and customize the UI, rather than a CLI bulk tool to extract data. But the concept is similar. I also intend to build up a catalog of expressions to extract different parts of the screen, and wondered if this part could be pulled out into a separate community repo that everyone can benefit from. Thoughts?

**Comment by harismuneer** [comment]
@matt-kruse let's chat on LinkedIn https://www.linkedin.com/in/harismuneer/ and discuss this more. Which part of the repo are you referring to specifically btw?
