### ISSUE TITLE
Can't get post, friends

### ISSUE THREAD

**Issue by arifrahman2592** [harismuneer/Ultimate-Facebook-Scraper#20]
I'm trying to following tutorial, and get the basic profile information, and also get Post.txt too, but not text status, video, photos
![has](https://user-images.githubusercontent.com/48396277/54217282-ec292b80-451d-11e9-8ada-a22274d44d77.PNG)

**Comment by torsteinringnes** [comment]
Same goes for me.

**Comment by albbrt** [comment]
Same. I'll try to put my hands on the code with a collegue just to fix Friends, which is what I need. Facebook must have changed something a few weeks ago, since even my mostly manual method to get a friends list with regular expressions fails.

**Comment by NTgitdude23** [comment]
Is this issue with friends list still going on or has it been resolved?   Thanks in advance..

**Comment by github-userx** [comment]
Also would like to know if this has been resolved. I wished we had more active contributors on here

**Comment by omar13essam** [comment]
Also for me 
Posts: Could not map encoded characters

**Comment by harismuneer** [comment]
I have fixed the script. Now its scraping the friends and photos :)

**Comment by harismuneer** [comment]
I have fixed the script. Facebook modifies their website every few days, that's why I have to maintain UFS so that it keeps on working perfectly.
