### ISSUE TITLE
Chromedriver Version

### ISSUE THREAD

**Issue by Eisblume77** [harismuneer/Ultimate-Facebook-Scraper#22]
Hi,
i got the following error:

`Marcos-MBP:Code marco$ python3 scraper.py

Enter your Facebook Email: maxmustermann@gmail.com
Password:

Starting Scraping...
Kindly replace the Chrome Web Driver with the latest one fromhttp://chromedriver.chromium.org/downloads
Your OS: darwin`

Tried on latest MacOS. Can you explain me, how to change the driver ??

Thx in advance, 
Marco

**Comment by pretech86** [comment]
the same problem with me also i use linux os

**Comment by Thurnun** [comment]
I have the same problem with linux, Regardless of adding the latest stable or beta chrome driver I still get the "Kindly replace the Chrome Web Driver with the latest one fromhttp://chromedriver.chromium.org/downloads"

**Comment by pretech86** [comment]
any one can help us

**Comment by ArtaMoaser** [comment]
Hi 
I had the same problem, I found out that I have chrome browser in my system that version was 73, I just downloaded the same version from http://chromedriver.chromium.org/downloads and code was run!

**Comment by Eisblume77** [comment]
Thx. Version 73 works !!!!
