### ISSUE TITLE
chromume error 

### ISSUE THREAD

**Issue by pretech86** [harismuneer/Ultimate-Facebook-Scraper#25]
thanks for your efforts ,, i have the following error 

Starting Scraping...
Kindly replace the Chrome Web Driver with the latest one fromhttp://chromedriver.chromium.org/downloads
Your OS: linux

can you help please

**Comment by harismuneer** [comment]
You can try to download the latest chrome driver version for Linux from this site: [](http://chromedriver.chromium.org/downloads)

Also make sure that you have the latest Chrome browser version on your computer. The versions of Chrome Web Driver and Chrome Browser should be same. This is also mentioned on the above link.
