### ISSUE TITLE
gl_surface_egl.cc error and Could not map encoded characters error.

### ISSUE THREAD

**Issue by DanielGutema** [harismuneer/Ultimate-Facebook-Scraper#26]
Hi!
I want to scrape all the text from someones profile, (to use it for machine learning in a school project, i have consent to scrape this data from the person) , but i cant get the texts.

The scraper process completes, gets me everything BUT the text data (what i actually need) , i get a lot of the same two errors displayed on the screenshot. 

I get life events, check-ins and photo uploads but not the text that the person posted.
Does anyone have the same issue?
Could anyone tell me what's the problem?
(i couldn't find anything on stackoverflow)

I am using 32-bit google chrome, with the latest chromedriver, cant get the text data but everything else works.

![POSTS OUTPUT](https://user-images.githubusercontent.com/49904569/56573954-6d1a1f00-65c2-11e9-8136-b24dc5979aaa.jpg)
![CMD OUTPUT](https://user-images.githubusercontent.com/49904569/56573955-6d1a1f00-65c2-11e9-8f6f-0d1076b07925.jpg)

**Comment by harismuneer** [comment]
### 📢 Important Announcement: UFS 2.0 (with support for latest Facebook UI)

Hi guys! The exclusive version of **UFS 2.0** supports scraping for the latest Facebook UI along with many powerful features, much better organization through CSV (Excel-like) file format, bug fixes, and multiple browser support. You can get exclusive access here: 

#### **[Buy UFS 2.0](https://tinyurl.com/UFS-NEW)** 

Building the new version has been a tough technical challenge and I have spent a considerable amount of time and effort on building it. Therefore, kindly support by purchasing it from the link shared [above.](https://tinyurl.com/UFS-NEW) 

<hr>
You can also share small donations through these links:


- <a href="https://buy.paddle.com/product/638653"><b>Platinum (99.99$)</b> -> 2 hours of development<a/>
- <a href="https://buy.paddle.com/product/638651"><b>Gold (49.99$)</b> -> 1 hour of development</a>
- <a href="https://buy.paddle.com/product/638654"><b>Silver (19.99$)</b> -> 30 minutes of development</a>

_If **considerable support is shown through the above donations then I will release the version for the general public** after some time as I want to keep this software open-sourced. So, now is the time for all those folks who benefited from the tool to support its reach for a wider audience :)_
