### ISSUE TITLE
Please, i need help. Friends, photos and videos are not downloaded.

### ISSUE THREAD

**Issue by chelsas69** [harismuneer/Ultimate-Facebook-Scraper#27]
The crawler just gives me the profile information, but nothing is downloaded. A few months ago it worked perfectly. Could Facebook have changed something?
![cap](https://user-images.githubusercontent.com/47102233/57031499-2bcfe200-6c48-11e9-9b8c-85cde345d917.png)

![cap2](https://user-images.githubusercontent.com/47102233/57031539-43a76600-6c48-11e9-8110-9634ee6af5c1.png)

**Comment by kalaivendran** [comment]
Yes, I am having the same issues. Anyone has a solution for this?

**Comment by github-userx** [comment]
@harismuneer @Hassaan-Elahi 
Will You still Update or keep working on UltimateFacebookScraper? Its been such a beautiful Tool in the past, working so flawless - but now it seems to be broken

**Comment by harismuneer** [comment]
@github-userx 
Currently we are extremely occupied by the final exams of our CS degree. So after 15 to 20 days, we will solve all these issues and make the tool run again perfectly.

**Comment by github-userx** [comment]
That sound absolute perfect Haris! I wish You both the best of luck for Your exams!

**Comment by awaiskhawaj** [comment]
> @github-userx
> Currently we are extremely occupied by the final exams of our CS degree. So after 15 to 20 days, we will solve all these issues and make the tool run again perfectly.
i am getting error in creating profile directory how this can be solved.

**Comment by github-userx** [comment]
@awaiskhawaj Haris already mentioned that they are gonna fix all issues after they did their exams.

Also, you should describe what you did, tried and what didn‘t work in more detail next time.

**Comment by github-userx** [comment]
@daaanny90 would you be interested in collaborating/ helping this Ultimate Facebook Scraper? I saw your own Facebook Photos Selenium project.
We should unite forces ;)

**Comment by daaanny90** [comment]
@github-userx I don't have much time right now, but I will check it out :)

**Comment by github-userx** [comment]
@daaanny90 awesome!

**Comment by Jingo91** [comment]
Hey guys,
when do you think, you can address the problem? I think the main problem here is, that the elements_path have been changed, but I didn't get it fixed now. 
Would be nice to know, how long I have to wait, because otherwise I have to do it "crawl" manually to make it in time.

**Comment by github-userx** [comment]
@Jingo91 like Haris said: in now maybe around ten days, after their exams.
personally, I don’t think any other tool comes even close to UFS‘s capabilities and doing everything manually has always been a super PITA IMHO (saving hundreds of photos manually).
thanks for your suggestion regarding elements_path

3 June 2019, 16:33 from notifications@github.com <mailto:notifications@github.com>:

**Comment by Jingo91** [comment]
He said after 15-20 days.. and that was 16 days ago, so I thought I'll ask :(

**Comment by khahu132** [comment]
Hope can see your tool run again

**Comment by github-userx** [comment]
Fair enough. Let’s just be patient :)

**Comment by kidspro88** [comment]
Hope to hearing good news from you soon. @harismuneer

**Comment by harismuneer** [comment]
Hi everyone.

Apologies for the delay. I just started working as a full time Software Engineer so previous week was really work intensive. This weekend I will merge the pull requests and make sure the tool is running smoothly again. Thanks for your support :)

**Comment by 3nomis** [comment]
Same issue.

**Comment by harismuneer** [comment]
Hi guys!

I have fixed all bugs related to the functionalities of Friends, Photos and Videos. The tool is now working perfectly. Cheers! :)

**Comment by github-userx** [comment]
@harismuneer You’re truly a saint! Many many thanks!
