### ISSUE TITLE
I am using the latest version of chrome driver and while running the code on my linux machine, I'm getting the replace chrome driver error.

### ISSUE THREAD

**Issue by shikharp16** [harismuneer/Ultimate-Facebook-Scraper#3]

**Comment by harismuneer** [comment]
Hi shikharp

Kindly re-verify that you are using the latest chrome driver version available for Linux. Try replacing it with the latest one available at: http://chromedriver.chromium.org/downloads

There might have been a new release of the chrome driver version. So try replacing it with the latest one and let me know.

**Comment by shikharp16** [comment]
Hey! Thanks for your help.
 I updated my google chrome version from 67.x to 69.x and after the update, your extension worked perfectly.

**Comment by pretech86** [comment]
i update it and still the same error 
can you help me please
