### ISSUE TITLE
get_status not getting content

### ISSUE THREAD

**Issue by Sydrik** [harismuneer/Ultimate-Facebook-Scraper#31]
This relates to the output that should appear in Posts.txt

Tested this on several account profiles and also made sure that the posts contain something. They also are found in div with class that contains 'userContent'. However, the output in Posts.txt shows all data except for the content.

Did put in a print statement in get_status and it shows that _status = x.find_element_by_xpath("//div[@class='userContent']").text_ is called. Status however returns an empty value.

**Comment by harismuneer** [comment]
I have fixed all the bugs related to Friends, Photos, Videos and About sections. Next target is this bug related to Posts. Many people are facing this issue, so I will be working on this now. Currently I am working as a full-time engineer, that's why its getting really difficult for me to maintain this repo. I worked the whole day today to fix the script. 

Anyways, I will try to fix this asap. Thanks for your support and patience :)

**Comment by aguhob** [comment]
I'm having this same issue. Has there been any progress with the fix related to Posts?

**Comment by harismuneer** [comment]
### 📢 Important Announcement: UFS 2.0 (with support for latest Facebook UI)

Hi guys! The exclusive version of **UFS 2.0** supports scraping for the latest Facebook UI along with many powerful features, much better organization through CSV (Excel-like) file format, bug fixes, and multiple browser support. You can get exclusive access here: 

#### **[Buy UFS 2.0](https://tinyurl.com/UFS-NEW)** 

Building the new version has been a tough technical challenge and I have spent a considerable amount of time and effort on building it. Therefore, kindly support by purchasing it from the link shared [above.](https://tinyurl.com/UFS-NEW) 

<hr>
You can also share small donations through these links:


- <a href="https://buy.paddle.com/product/638653"><b>Platinum (99.99$)</b> -> 2 hours of development<a/>
- <a href="https://buy.paddle.com/product/638651"><b>Gold (49.99$)</b> -> 1 hour of development</a>
- <a href="https://buy.paddle.com/product/638654"><b>Silver (19.99$)</b> -> 30 minutes of development</a>

_If **considerable support is shown through the above donations then I will release the version for the general public** after some time as I want to keep this software open-sourced. So, now is the time for all those folks who benefited from the tool to support its reach for a wider audience :)_
