### ISSUE TITLE
Not Scrolling?

### ISSUE THREAD

**Issue by abigailzeng** [harismuneer/Ultimate-Facebook-Scraper#32]
This relates to the part of codes dealing with posts.

I used scraper.py to scrape the posts from facebook company users (the pages of which have a slightly different html structure from those of the individual users). I managed to revise the xpath accordingly and when I printed the results, it seems that the posts were indeed captured. However, it only return the first few posts (around 20 or so) from the pages, not all the posts of an account. When I did a test, it seems that the function scroll() is only called once. Is that supposed to be the case?

Thank you!

**Comment by github-userx** [comment]
I just tried the most recent version of UFS as well and it only scraped the first 15-20 friends (list and photos) instead of the full 600 friends of that person.

It also didn’t download any of the main users profile pictures.

**Comment by harismuneer** [comment]
@abigailzeng @github-userx 

When I was fixing the script yesterday, I set the scroll count to 0 and turned off the boolean variables to download friend's photos and uploaded photos. 

I have mentioned in the Readme file as well that how can you configure these options according to your need but for your convenience I have turned them on and pushed the latest code. You can check that now.

**Comment by harismuneer** [comment]
@abigailzeng 

You are welcome generate a pull request for the Post's feature that you modified for the new type of Users :)
