### ISSUE TITLE
Retrieve also Photos-Tagged / Photos-of via Graphsearch workaround

### ISSUE THREAD

**Issue by github-userx** [harismuneer/Ultimate-Facebook-Scraper#33]
Via @sowdust 's [Fantastic Firefox-Addon](https://github.com/sowdust/searchbook) it is still possible to find a users tagged photos - even if you’re not friends with them. 

You just have to use either the

   intersect(photos-tagged(facebook-userID))
or
    intersect(photos-of(facebook-userID))

Parameter and the search page gets modified accordingly.

As you know, before the graph search changes the tagged photos could just easily be found via the official graph search URL: facebook.com/search/facebook-userID/photos-tagged as well as  facebook.com/search/facebook-userID/photos-of but this isn’t possible anymore and therefore makes it much more difficult for UFS to get a hold of this information/These Photos.

**Comment by harismuneer** [comment]
@github-userx 

I tested UFS yesterday and it was able to get tagged photos of a profile. But I will surely look into this matter in depth :)

**Comment by github-userx** [comment]
A profile you aren’t friends with? I might also check my Facebook language settings etc. - but generally I feel like lot of information on fb recently got better protected.

1-2 years ago many „privacy settings“ actually never really protected your profile from preying eyes.

I will also get the most recent version from chromedriver, I think I used the one from the Ubuntu repositories

**Comment by harismuneer** [comment]
Oh, I actually thought you were talking about the tagged photos of a person with whom you are a friend with. This is interesting... I will surely look into this.

**Comment by github-userx** [comment]
Thanks!

Yes, I mostly scrape profiles I am not friends with for OSINT purposes.

For more information about the tagged photos graph search thing:

https://gist.github.com/nemec/2ba8afa589032f20e2d6509512381114

Which resulted in the creation of this Facebook search page and Firefox Addon by @sowdust :

https://sowdust.github.io/fb-search/

https://techblog.mediaservice.net/2019/06/facebook-graphs-not-dead/

**Comment by github-userx** [comment]
I assumed that UFW had always been capable of retrieving tagged photos from non-friends profiles, even before the graph search changes.

Because before Facebook removed these graph search URLs, UFS could simply get tagged photos from the very simple graph search URL Facebook.com/search/UserID/photos-tagged

**Comment by github-userx** [comment]
@harismuneer did you already have time to look into the potential integration of graphsearch workarounds into UFS? In particular the one of getting a persons tagged photos even if you’re not friends with that user.
@sowdust just updated his Firefox extension to perform graphsearch-like requests.

I doubt that this would be easy to integrate into UFS‘s capabilities but I have strong faith in Your skills. ;)

**Comment by harismuneer** [comment]
### 📢 Important Announcement: UFS 2.0 (with support for latest Facebook UI)

Hi guys! The exclusive version of **UFS 2.0** supports scraping for the latest Facebook UI along with many powerful features, much better organization through CSV (Excel-like) file format, bug fixes, and multiple browser support. You can get exclusive access here: 

#### **[Buy UFS 2.0](https://tinyurl.com/UFS-NEW)** 

Building the new version has been a tough technical challenge and I have spent a considerable amount of time and effort on building it. Therefore, kindly support by purchasing it from the link shared [above.](https://tinyurl.com/UFS-NEW) 

<hr>
You can also share small donations through these links:


- <a href="https://buy.paddle.com/product/638653"><b>Platinum (99.99$)</b> -> 2 hours of development<a/>
- <a href="https://buy.paddle.com/product/638651"><b>Gold (49.99$)</b> -> 1 hour of development</a>
- <a href="https://buy.paddle.com/product/638654"><b>Silver (19.99$)</b> -> 30 minutes of development</a>

_If **considerable support is shown through the above donations then I will release the version for the general public** after some time as I want to keep this software open-sourced. So, now is the time for all those folks who benefited from the tool to support its reach for a wider audience :)_
