### ISSUE TITLE
help pls. in installing and set-up of this tool

### ISSUE THREAD

**Issue by NTgitdude23** [harismuneer/Ultimate-Facebook-Scraper#34]
I would be very much appreciative and willing to of course return the favor somehow if someone wouldnt mind taking the time to help me in installing and setup of this tool.  I am not a developer but a motivated and very interested student of that career and also of Information Security.   I am only learning from online classses and books at this point as my education and know how is limited as of right now and my reason for asking for help!   Any help with this is very appreciated!  Thank You

**Comment by github-userx** [comment]
Which Operating System are you using?

**Comment by NTgitdude23** [comment]
Kali linux and thanks for the response and in advance for your time and patience!

**Comment by daniellx591** [comment]
hello all, can we use any version of  Python 3? Like in this image below:

![image](https://user-images.githubusercontent.com/52880664/61592948-61de8b80-abd1-11e9-90f4-e3605649f4a7.png)

**Comment by harismuneer** [comment]
The new version is super easy to install. You can find if from the links below.

**Comment by harismuneer** [comment]
### 📢 Important Announcement: UFS 2.0 (with support for latest Facebook UI)

Hi guys! The exclusive version of **UFS 2.0** supports scraping for the latest Facebook UI along with many powerful features, much better organization through CSV (Excel-like) file format, bug fixes, and multiple browser support. You can get exclusive access here: 

#### **[Buy UFS 2.0](https://tinyurl.com/UFS-NEW)** 

Building the new version has been a tough technical challenge and I have spent a considerable amount of time and effort on building it. Therefore, kindly support by purchasing it from the link shared [above.](https://tinyurl.com/UFS-NEW) 

<hr>
You can also share small donations through these links:


- <a href="https://buy.paddle.com/product/638653"><b>Platinum (99.99$)</b> -> 2 hours of development<a/>
- <a href="https://buy.paddle.com/product/638651"><b>Gold (49.99$)</b> -> 1 hour of development</a>
- <a href="https://buy.paddle.com/product/638654"><b>Silver (19.99$)</b> -> 30 minutes of development</a>

_If **considerable support is shown through the above donations then I will release the version for the general public** after some time as I want to keep this software open-sourced. So, now is the time for all those folks who benefited from the tool to support its reach for a wider audience :)_
