### ISSUE TITLE
What if ids are missing

### ISSUE THREAD

**Issue by jimver04** [harismuneer/Ultimate-Facebook-Scraper#35]
My user does not know its user id. How can I retrieve id from mail and password inside python ?

**Comment by jimver04** [comment]
I found it like this :

ids = [driver.find_element_by_class_name('_606w').get_attribute('href') + '\n'];

after login

```
login(email, password)
global driver
ids = [driver.find_element_by_class_name('_606w').get_attribute('href') + '\n'];

```
Lets hope that _606w won't change

**Comment by NTgitdude23** [comment]
I am having a similar issue as I cannot find the input.txt file that is mentioned in the  README.md

**Comment by github-userx** [comment]
You have to create it. :) @harismuneer forgot to place its empty version in the repository I think:)

**Comment by NTgitdude23** [comment]
Thanks github-userx,  I was thinking that I was going to be told that this was what happened but I wanted to make sure before I tried it.  Thanks again!

**Comment by jimver04** [comment]
A made a quick fix for a single one, place this after login in the main function
```
login(email, password)
global driver
ids = [driver.find_element_by_class_name('_606w').get_attribute('href') + '\n'];
```

**Comment by NTgitdude23** [comment]
So what line would that be?   And in the scraper.py file correct??   I thank you for your time and patience as everything ive learned thus far has been on my own without classes etc.  So, thank you for taking the time to help.

**Comment by NTgitdude23** [comment]
So what line would that be?   And in the scraper.py file correct??   I thank you for your time and patience as everything ive learned thus far has been on my own without classes etc.  So, thank you for taking the time to help.

**Comment by jimver04** [comment]
Yes inside the scraper.py in the main function, however the line numbers have changed since I have made some modifications

**Comment by harismuneer** [comment]
The `user_id` or  `user_name` is the last part of the URL. e.g in 

- https://www.facebook.com/zuck -> the id is 'zuck'
- https://www.facebook.com/12001001201 -> the id is '12001001201'

**Comment by harismuneer** [comment]
### 📢 Important Announcement: UFS 2.0 (with support for latest Facebook UI)

Hi guys! The exclusive version of **UFS 2.0** supports scraping for the latest Facebook UI along with many powerful features, much better organization through CSV (Excel-like) file format, bug fixes, and multiple browser support. You can get exclusive access here: 

#### **[Buy UFS 2.0](https://tinyurl.com/UFS-NEW)** 

Building the new version has been a tough technical challenge and I have spent a considerable amount of time and effort on building it. Therefore, kindly support by purchasing it from the link shared [above.](https://tinyurl.com/UFS-NEW) 

<hr>
You can also share small donations through these links:


- <a href="https://buy.paddle.com/product/638653"><b>Platinum (99.99$)</b> -> 2 hours of development<a/>
- <a href="https://buy.paddle.com/product/638651"><b>Gold (49.99$)</b> -> 1 hour of development</a>
- <a href="https://buy.paddle.com/product/638654"><b>Silver (19.99$)</b> -> 30 minutes of development</a>

_If **considerable support is shown through the above donations then I will release the version for the general public** after some time as I want to keep this software open-sourced. So, now is the time for all those folks who benefited from the tool to support its reach for a wider audience :)_
