### ISSUE TITLE
scraper.py:610: DeprecationWarning: use options instead of chrome_options   driver = webdriver.Chrome(executable_path="./chromedriver.exe", chrome_options=options) Kindly replace the Chrome Web Driver with the latest one from http://chromedriver.chromium.org/downloads

### ISSUE THREAD

**Issue by lostradamu** [harismuneer/Ultimate-Facebook-Scraper#4]
I have replaced with the latest Chrome Driver and still encounter the above error. 

Chrome version: Version 70.0.3538.67 (Official Build) (64-bit)
Chrome Driver: https://chromedriver.storage.googleapis.com/index.html?path=2.43/
Selenium:  3.14.1

**Comment by jblann** [comment]
Have the same issue.

**Comment by lostradamu** [comment]
@jblann macOS 10.12.6 although I was receiving the same error when I attempted to run it on Windows 10 Pro.

**Comment by jblann** [comment]
Its not the fix but I am still working on it,  To kick off the scraper I placed a # on line 609 and 610 of scraper.py
            #else:
                #driver = webdriver.Chrome(executable_path="./chromedriver", chrome_options=options)

I did everything with regards to editing my Firewall to creating a Self-signed Cert.

Now I have a whole new set of issues, scraper hangs and no final deliverables.

**Comment by jblann** [comment]
Need to reach out to @harismuneer when I get a breather.

**Comment by harismuneer** [comment]
@lostradamu and @jblann, try replacing the 'chrome_options' with 'options' in lines 608 and 610 of scraper.py:

Currently the lines are:

```            
if platform.system() == 'Linux':
     driver = webdriver.Chrome(executable_path="./chromedriver", chrome_options=options)
else:
     driver = webdriver.Chrome(executable_path="./chromedriver.exe", chrome_options=options)
```

Change them to:

```
if platform.system() == 'Linux': 
     driver = webdriver.Chrome(executable_path="./chromedriver", options=options)
else:
     driver = webdriver.Chrome(executable_path="./chromedriver.exe", options=options)
```

That's a minor depreciation warning which is being caught by the 'except' in line 611 due to which you are always getting the message to update your chrome driver. Let me know if this fixes the issue so that I can update the master code with this fix. Also, apologies for getting back a bit lately, I have been a lot these days.

**Comment by jblann** [comment]
Haris Muneer
Hey! No worries on the delay!  This is the output:

Starting Scraping...
Kindly replace the Chrome Web Driver with the latest one from http://chromedriver.chromium.org/downloads

So the depreciation warning is gone but the code says Starting Scraping but than returns to prompt no output of data and no execution of scraping.

**Comment by harismuneer** [comment]
@jblann in the try-except block on lines 606-614, add the following line of code in the except block to print the original exception message and share the message with me. 

```
        except Exception as e:
            print(str(e))
            #print("Kindly replace the Chrome Web Driver with the latest one from"
                  " http://chromedriver.chromium.org/downloads")
            exit()
```

**Comment by jblann** [comment]
except Exception as e:
            print(str(e))
            #print("Kindly replace the Chrome Web Driver with the latest one from"
                  " http://chromedriver.chromium.org/downloads"**)**
            exit()

The extra parenthesis after downloads") gave me an invalid syntax error.  Dropped the parenthesis:

 except Exception as e:
            print(str(e))
            #print("Kindly replace the Chrome Web Driver with the latest one from"
                  " http://chromedriver.chromium.org/downloads"
            exit()

And the scraper kicked off without an error but, the chrome browser started the out put said
Starting Scraping...
Then returned to command prompt and the browser hung with no collection.

**Comment by jblann** [comment]
joe:code joe$ python scraper.py
  File "scraper.py", line 615
    " http://chromedriver.chromium.org/downloads"))
                                                 ^
SyntaxError: invalid syntax
joe:code joe$ python scraper.py

Enter your Facebook Email: ***********
Enter your Facebook Password: ***************************

Starting Scraping...
joe:code joe$

**Comment by jblann** [comment]
<img width="1190" alt="screen shot 2018-10-27 at 2 53 16 pm" src="https://user-images.githubusercontent.com/22334478/47608210-13141480-d9f8-11e8-8184-781c428b53b0.png">
The browser had this in the url

**Comment by jblann** [comment]
Thank you for helping with this issue!

**Comment by iGorEremenko** [comment]
Please tell me how you can manage the process of parsing - for example, remove those sections of parsing that I don’t need such as Contact and Basic Info.txt, Details About.txt, Family and Relationships.txt, Life Events.txt and so on. I was able to turn off the photo but I only need posts from the pages, please forgive me for my English, I am from Ukraine

**Comment by packetique** [comment]
options=options
It's helped me. Also I'm used options.add_argument("--ignore-certificate-errors")
Python, win10
