### ISSUE TITLE
Temporarily Blocked

### ISSUE THREAD

**Issue by BabyRdx** [harismuneer/Ultimate-Facebook-Scraper#45]
Appears Facebook has some sort of internal limiter.  
I set about scrapping one profile and by setting both of the image save variables to false (to download high res photos).  After around 30 friends in I got hit with a Facebook error page:

> You’re Temporarily Blocked
> It looks like you were misusing this feature by going too fast. You’ve been blocked from using it.

I can't use a dummy account as the target account isn't friends with the dummy account.  Perhaps add a wait function into the code so that it waits a random amount of time between requests rather than spamming asap.

**Comment by Erk011** [comment]
Hello, i really want know how you did for it work, im trying but can´t do it work

**Comment by InsaneJokerr** [comment]
See [You've been temporarily blocked - Facebook #48](https://github.com/harismuneer/Ultimate-Facebook-Scraper/issues/48). This will be a rate limit from Facebook. This is blocking the script from working as it should. We've tried many ways to work around this, but the rate limiter is aggressive. we failed to find a fix.

**Comment by carlosalaniz** [comment]
[https://github.com/harismuneer/Ultimate-Facebook-Scraper/issues/48#issuecomment-612744564](https://github.com/harismuneer/Ultimate-Facebook-Scraper/issues/48#issuecomment-612744564)

**Comment by harismuneer** [comment]
### 📢 Important Announcement: UFS 2.0 (with support for latest Facebook UI)

Hi guys! The exclusive version of **UFS 2.0** supports scraping for the latest Facebook UI along with many powerful features, much better organization through CSV (Excel-like) file format, bug fixes, and multiple browser support. You can get exclusive access here: 

#### **[Buy UFS 2.0](https://tinyurl.com/UFS-NEW)** 

Building the new version has been a tough technical challenge and I have spent a considerable amount of time and effort on building it. Therefore, kindly support by purchasing it from the link shared [above.](https://tinyurl.com/UFS-NEW) 

<hr>
You can also share small donations through these links:


- <a href="https://buy.paddle.com/product/638653"><b>Platinum (99.99$)</b> -> 2 hours of development<a/>
- <a href="https://buy.paddle.com/product/638651"><b>Gold (49.99$)</b> -> 1 hour of development</a>
- <a href="https://buy.paddle.com/product/638654"><b>Silver (19.99$)</b> -> 30 minutes of development</a>

_If **considerable support is shown through the above donations then I will release the version for the general public** after some time as I want to keep this software open-sourced. So, now is the time for all those folks who benefited from the tool to support its reach for a wider audience :)_
