### ISSUE TITLE
Select what data is scraped

### ISSUE THREAD

**Issue by InsaneJokerr** [harismuneer/Ultimate-Facebook-Scraper#49]
Is there a way to omit certain data being scraped from each profile. 

i.e. exclude posts from being pulled.

**Comment by SyahirahWanMin** [comment]
simply just remove status = 4 in code which is for post

**Comment by DanielOberlechner** [comment]
@InsaneJokerr at the moment it isn't possible to skip anything.
It shouldn't be much work to program something like that but would it be worth it?

If you scrape just some normal profiles it doesn't take long until it is done therefore it does not really make sense ...

Greets Daniel

**Comment by InsaneJokerr** [comment]
Hi Daniel, 

It is possible, I should have updated this thread, but I've lost track slightly working on another project. Removing lines of the code from 521 onwards alows you to stop the code from scraping particular parts of a profile. 

In my example, I had no need for profile photos, so I removed the part of the code that scraped these.

^KJ
