### ISSUE TITLE
no "input.txt" file to be found

### ISSUE THREAD

**Issue by OMGdaDPS** [harismuneer/Ultimate-Facebook-Scraper#52]
I have just cloned the repo, and extracted the contents, but I cannot find any "input.txt" file, which is the location that we are supposed to put the profiles that we want to scrape in. Am I missing something here?

**Comment by SyahirahWanMin** [comment]
You need to create all files by your own. then change all the directory in code

**Comment by OMGdaDPS** [comment]
Right on, thank you. I don't want to be knit picky, but it doesn't say that in the README. It actually says right under the "How To Run" section, that there IS a file named "input.txt". You may want to clarify that, if a person has to create it themselves.

**Comment by DavidPerea** [comment]
One question, what should I write to the "input.txt" file in order to collect facebook data? I'm not sure what code I should write

**Comment by SkYNewZ** [comment]
Read the doc : https://github.com/harismuneer/Ultimate-Facebook-Scraper#how-to-run
