### ISSUE TITLE
Downloaded photos are very low quality

### ISSUE THREAD

**Issue by jakehart** [harismuneer/Ultimate-Facebook-Scraper#54]
I think the scraper is downloading thumbnails, not full-resolution photos. Every picture is extremely pixelated. I verified that the originals on Facebook don't suffer from this problem, so it's definitely an issue with the scraper.

**Comment by SkYNewZ** [comment]
Just read the doc https://github.com/harismuneer/Ultimate-Facebook-Scraper#how-to-run 😉

**Comment by jakehart** [comment]
Oops, thank you!
