### ISSUE TITLE
Facebook lock

### ISSUE THREAD

**Issue by MaxFallishe** [harismuneer/Ultimate-Facebook-Scraper#6]
"""
You’re Temporarily Blocked
It looks like you were misusing this feature by going too fast. You’ve been blocked from using it.

Learn more about blocks in the Help Center.
"""

How can this problem be solved?

**Comment by jblann** [comment]
Question:  Have you setup a developer account for the Facebook profile you are using to aggregate data?

**Comment by regina-avila** [comment]
Error:
scraper.py:610: DeprecationWarning: use options instead of chrome_options
  driver = webdriver.Chrome(executable_path="./chromedriver.exe", chrome_options=options)
I'm using a Mac, do I need to change  " if platform.system() == 'Linux':"?

**Comment by github-userx** [comment]
@jblann I thought this fb scraper doesn't use any FB API? or were you asking OP because OP might use a developer account and you assumed this lead to OP's errors?

**Comment by harismuneer** [comment]
@MaxFallishe I guess there's some sort of issue with your Facebook account. I always recommend to use this scraper with some other dummy Facebook account of yours to avoid the risks. 

Moreover, @jblann the scraper doesn't use any of Facebook's APIs.
