### ISSUE TITLE
Can not scrap after making all the process mentioned in the readme

### ISSUE THREAD

**Issue by dennis104306007** [harismuneer/Ultimate-Facebook-Scraper#60]
After making all the process mentioned in the readme, execute the codes, I got this:
-------------------------------------------------------------------------------------------
Starting Scraping...
Kindly replace the Chrome Web Driver with the latest one from http://chromedriver.chromium.org/downloads and also make sure you have the latest Chrome Browser version.
Your OS: darwin
-------------------------------------------------------------------------------------------
Does that mean that the scraping is processing or I just failed?
Thx!

**Comment by arthurbarros** [comment]
on your src/ folder there is a file called chromedriver, you should replace that one with the one you download from the link you mentioned in your post

**Comment by rubcalvo** [comment]
I have ChromeDriver 78.0.3904.70 and Google Chrome Version 78.0.3904.70 (Official Build) (64-bit) and I'm still getting this error. Can anyone have a idea why?
Thanks

**Comment by dennislee928** [comment]
Still got thisproblem:(
download from the link you mentioned in your post
and still got
![Screen Shot 2019-10-25 at 1 50 46 PM](https://user-images.githubusercontent.com/55692615/67546249-7e3d1780-f72e-11e9-9c50-52e2fe74f875.png)
![Screen Shot 2019-10-25 at 1 50 25 PM](https://user-images.githubusercontent.com/55692615/67546252-81d09e80-f72e-11e9-8737-0d470d83b965.png)

**Comment by SkYNewZ** [comment]
> ## After making all the process mentioned in the readme, execute the codes, I got this:
> ## Starting Scraping...
> Kindly replace the Chrome Web Driver with the latest one from http://chromedriver.chromium.org/downloads and also make sure you have the latest Chrome Browser version.
> Your OS: darwin
> Does that mean that the scraping is processing or I just failed?
> Thx!

@dennis104306007 
The Chromedriver change with latest commits. Do you still have this issue ? It should now automatically detect your OS ans the right associated chromedriver binard file.

**Comment by random-accountdel** [comment]
Kindly replace the Chrome Web Driver with the latest one from http://chromedriver.chromium.org/downloads and also make sure you have the latest Chrome Browser version.
Your OS: linux
I have installed latest chromium browser and also latest chrome driver, still facing the issue
I have this issue in kali linux @arthurbarros please help

**Comment by random-accountdel** [comment]
Kindly replace the Chrome Web Driver with the latest one from http://chromedriver.chromium.org/downloads and also make sure you have the latest Chrome Browser version.
Your OS: linux
I have installed latest chromium browser and also latest chrome driver, still facing the issue
I have this issue in kali linux @arthurbarros please help

**Comment by random-accountdel** [comment]
![aa](https://user-images.githubusercontent.com/62297673/76876362-d4565700-6897-11ea-9616-00b0816e1746.PNG)
@dennis104306007 @arthurbarros @rubcalvo @dennislee928 @SkYNewZ

**Comment by harismuneer** [comment]
### 📢 Important Announcement: UFS 2.0 (with support for latest Facebook UI)

Hi guys! The exclusive version of **UFS 2.0** supports scraping for the latest Facebook UI along with many powerful features, much better organization through CSV (Excel-like) file format, bug fixes, and multiple browser support. You can get exclusive access here: 

#### **[Buy UFS 2.0](https://tinyurl.com/UFS-NEW)** 

Building the new version has been a tough technical challenge and I have spent a considerable amount of time and effort on building it. Therefore, kindly support by purchasing it from the link shared [above.](https://tinyurl.com/UFS-NEW) 

<hr>
You can also share small donations through these links:


- <a href="https://buy.paddle.com/product/638653"><b>Platinum (99.99$)</b> -> 2 hours of development<a/>
- <a href="https://buy.paddle.com/product/638651"><b>Gold (49.99$)</b> -> 1 hour of development</a>
- <a href="https://buy.paddle.com/product/638654"><b>Silver (19.99$)</b> -> 30 minutes of development</a>

_If **considerable support is shown through the above donations then I will release the version for the general public** after some time as I want to keep this software open-sourced. So, now is the time for all those folks who benefited from the tool to support its reach for a wider audience :)_
