### ISSUE TITLE
I cannot scrape anything 

### ISSUE THREAD

**Issue by HelloNman** [harismuneer/Ultimate-Facebook-Scraper#66]
photos,viedio,posts cannot download,and have so many exceptions like this

Friends..
Exception (scrape_data) 0 Status = 0 <class 'selenium.common.exceptions.NoSuchElementException'>
Exception (scrape_data) 1 Status = 0 <class 'selenium.common.exceptions.NoSuchElementException'>
Exception (scrape_data) 2 Status = 0 <class 'selenium.common.exceptions.NoSuchElementException'>
Exception (scrape_data) 3 Status = 0 <class 'selenium.common.exceptions.NoSuchElementException'>
Exception (scrape_data) 4 Status = 0 <class 'selenium.common.exceptions.NoSuchElementException'>
Exception (scrape_data) 5 Status = 0 <class 'selenium.common.exceptions.NoSuchElementException'>
Exception (scrape_data) 6 Status = 0 <class 'selenium.common.exceptions.NoSuchElementException'>
Exception (scrape_data) 7 Status = 0 <class 'selenium.common.exceptions.NoSuchElementException'>
Friends Done!

**Comment by anoduck** [comment]
Just out of curiosity,
What OS are you running? What version of python? Did you watch it perform the scrape, or did you minimize the browser and leave it to run? 

Facebook has implemented new rate limiting policies that are aggressive. The same thing might be happening to you that are occurring to everyone else. Checkout Issue #48.

**Comment by kalaivendran** [comment]
Hi, am having the same issue. I saw it perform the scrape. Any solution?

**Comment by HelloNman** [comment]
I can not solve it, so I find some professional person to do a software that can scrape data.&nbsp;



---Original---

**Comment by InsaneJokerr** [comment]
> 
> 
> photos,viedio,posts cannot download,and have so many exceptions like this
> 
> Friends..
> Exception (scrape_data) 0 Status = 0 <class 'selenium.common.exceptions.NoSuchElementException'>
> Exception (scrape_data) 1 Status = 0 <class 'selenium.common.exceptions.NoSuchElementException'>
> Exception (scrape_data) 2 Status = 0 <class 'selenium.common.exceptions.NoSuchElementException'>
> Exception (scrape_data) 3 Status = 0 <class 'selenium.common.exceptions.NoSuchElementException'>
> Exception (scrape_data) 4 Status = 0 <class 'selenium.common.exceptions.NoSuchElementException'>
> Exception (scrape_data) 5 Status = 0 <class 'selenium.common.exceptions.NoSuchElementException'>
> Exception (scrape_data) 6 Status = 0 <class 'selenium.common.exceptions.NoSuchElementException'>
> Exception (scrape_data) 7 Status = 0 <class 'selenium.common.exceptions.NoSuchElementException'>
> Friends Done!

See [You've been temporarily blocked - Facebook #48](https://github.com/harismuneer/Ultimate-Facebook-Scraper/issues/48). This will be a rate limit from Facebook. This is blocking the script from working as it should. We've tried many ways to work around this, but the rate limiter is aggressive. we failed to find a fix.

**Comment by anoduck** [comment]
As of right now, this method of scraping the book of face is sitting dead in the water. Someone might work out a solution, someday. But, simply cloning this repo and running the script will not work at this moment.

**Comment by harismuneer** [comment]
### 📢 Important Announcement: UFS 2.0 (with support for latest Facebook UI)

Hi guys! The exclusive version of **UFS 2.0** supports scraping for the latest Facebook UI along with many powerful features, much better organization through CSV (Excel-like) file format, bug fixes, and multiple browser support. You can get exclusive access here: 

#### **[Buy UFS 2.0](https://tinyurl.com/UFS-NEW)** 

Building the new version has been a tough technical challenge and I have spent a considerable amount of time and effort on building it. Therefore, kindly support by purchasing it from the link shared [above.](https://tinyurl.com/UFS-NEW) 

<hr>
You can also share small donations through these links:


- <a href="https://buy.paddle.com/product/638653"><b>Platinum (99.99$)</b> -> 2 hours of development<a/>
- <a href="https://buy.paddle.com/product/638651"><b>Gold (49.99$)</b> -> 1 hour of development</a>
- <a href="https://buy.paddle.com/product/638654"><b>Silver (19.99$)</b> -> 30 minutes of development</a>

_If **considerable support is shown through the above donations then I will release the version for the general public** after some time as I want to keep this software open-sourced. So, now is the time for all those folks who benefited from the tool to support its reach for a wider audience :)_
