### ISSUE TITLE
not extracting friends

### ISSUE THREAD

**Issue by razvan1ilie** [harismuneer/Ultimate-Facebook-Scraper#72]
I've been trying for a couple of days and while it gets all other information it no longer retrieves the very important list of friends.
Is it working for you guys? Am I doing something wrong?
I've been running it on Linux from Python and on Windows from command prompt. Still no success.
Thank you!

**Comment by DanielOberlechner** [comment]
Hi,
do you mean the normal friend list? Or do you mean a personal list with very close friends?
I used the scraper today and I got the friend list written into AllFriends.txt ...

Can you describer further what do you mean?

Greets by Daniel :)

**Comment by harismuneer** [comment]
@DanielOberlechner thank you for helping out so many people in resolving the issues. Godspeed!

**Comment by harismuneer** [comment]
### 📢 Important Announcement: UFS 2.0 (with support for latest Facebook UI)

Hi guys! The exclusive version of **UFS 2.0** supports scraping for the latest Facebook UI along with many powerful features, much better organization through CSV (Excel-like) file format, bug fixes, and multiple browser support. You can get exclusive access here: 

#### **[Buy UFS 2.0](https://tinyurl.com/UFS-NEW)** 

Building the new version has been a tough technical challenge and I have spent a considerable amount of time and effort on building it. Therefore, kindly support by purchasing it from the link shared [above.](https://tinyurl.com/UFS-NEW) 

<hr>
You can also share small donations through these links:


- <a href="https://buy.paddle.com/product/638653"><b>Platinum (99.99$)</b> -> 2 hours of development<a/>
- <a href="https://buy.paddle.com/product/638651"><b>Gold (49.99$)</b> -> 1 hour of development</a>
- <a href="https://buy.paddle.com/product/638654"><b>Silver (19.99$)</b> -> 30 minutes of development</a>

_If **considerable support is shown through the above donations then I will release the version for the general public** after some time as I want to keep this software open-sourced. So, now is the time for all those folks who benefited from the tool to support its reach for a wider audience :)_
