### ISSUE TITLE
"Kindly replace the Chrome Driver with the latest one ... "

### ISSUE THREAD

**Issue by ludicpress** [harismuneer/Ultimate-Facebook-Scraper#77]
**Describe the bug**
I've followed the installation instructions you provide. I'm at the final stage where I want to use the ```ultimate-facebook-scraper``` command. When I run the command I receive the following message:

```Starting Scraping...```
```Kindly replace the Chrome Web Driver with the latest one from http://chromedriver.chromium.org/downloads and also make sure you have the latest Chrome Browser version.```
```Your OS: Linux```

I'm running the current version of Chrome and the latest Linux Chrome Web Driver (I also tried Windows). However, the current version of Chrome is ```78.0.3904.108``` and the latest Chrome Web Driver for Chrome 78 is ```78.0.3904.105```. This means Chrome and the Chrome Web Driver do not exactly match.

Is there a way to change the program so that Chrome and the Chrome Web Driver are compatible? Many thanks for your assistance.

**Desktop (please complete the following information):**
 - OS: Windows 10, but running through Ubuntu 18.04 application.
 - Python version: 3.7.5
 - Version: e968db7

**Comment by DanielOberlechner** [comment]
Hi,
I tried also to run the script via windows but no chance ...
It says the chrome web driver version is not the latest ...

Any idea what we could do to fix this?

Greets from Italy,
Daniel

**Comment by meetgyn** [comment]
**I can't make it work at all.**

Starting Scraping...
Kindly replace the Chrome Web Driver with the latest one from http://chromedriver.chromium.org/downloads and also make sure you have the latest Chrome Browser version.
Your OS: linux
(venv) root@kali:/opt/compliance/Ultimate-Facebook-Scraper/venv/bin#

**Comment by DanielOberlechner** [comment]
@meetgyn when the chrome version is not the same as the driver version this error occurs. try to install again the normal chrome or download the right version from the website ..

If you have further questions don't hesitate to contact me :)

Greets Daniel

**Comment by hungnt31** [comment]
I am using google chrome version 79.0.3945.88 win 64 bit, and version ChromeDriver 79.0.3945.36 also has the same error above of @DanielOberlechner. I am toxic in ChromeDriver, can version 79 for googlechrome 79 versions? Please help me do this. Thank you very much

**Comment by PremDutta** [comment]
whenever i run this command  ultimate-facebook-scraper
it's says 
ultimate-facebook-scraper : The term 'ultimate-facebook-scraper' is not recognized as the name of a cmdlet, function, script file, or operable program. 
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1

**Comment by DanielOberlechner** [comment]
@PremDutta 
Open the project folder in the terminal and change to the first folder.
Then enter this command into your terminal:
python3 scraper/scraper.py

Can you tell me which OS your using?

I hope this helps,
Greets by Daniel :)

**Comment by PremDutta** [comment]
Hi,
Windows 10
[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
28/12/19,
08:52:21 pm

**Comment by PremDutta** [comment]
Hi,
Its throwing an error
Traceback (most recent call last):
  File "scraper/scraper.py", line 6, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
28/12/19,
08:55:39 pm

**Comment by PremDutta** [comment]
I've already updated the chromium driver and pasted it on folder but it's
still not working

Starting Scraping...
Kindly replace the Chrome Web Driver with the latest one from
http://chromedriver.chromium.org/downloads and also make sure you have the
latest Chrome Browser version.
Your OS: windows


[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
28/12/19,
09:02:05 pm

**Comment by PremDutta** [comment]
Anyway!
Thank you So much
I solved my all issues.

Can we do the same thing with Instagram?
Is it possible



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
28/12/19,
09:26:18 pm

**Comment by fer0m** [comment]
Hi!
I have a same problem, don't know, what I should do.

"Kindly replace the Chrome Web Driver with the latest one from http://chromedriver.chromium.org/downloads and also make sure you have the latest Chrome Browser version.
Your OS: linux"

```
$chromedriver -v
$ChromeDriver 80.0.3987.106 (f68069574609230cf9b635cd784cfb1bf81bb53a-refs/branch-heads/3987@{#882})

$google-chrome -version
$Google Chrome 80.0.3987.132
```

Chrome webdriver working, for example:

```
from selenium import webdriver
driver = webdriver.Chrome()
driver.get("https://www.google.ru/")
```

, but when I want to Scrapper use - error. 
Help me please :)

**Comment by zahil** [comment]
hi, i've same problem. i'm using ubuntu 18.04

this is my chrome and chromedriver versio :
(venv) zahil1005@IT-JN1-Reza:~/Ultimate-Facebook-Scraper$ google-chrome --version
Google Chrome 80.0.3987.149
(venv) zahil1005@IT-JN1-Reza:~/Ultimate-Facebook-Scraper$ chromedriver --version
ChromeDriver 80.0.3987.87 (449cb163497b70dbf98d389f54e38e85d4c59b43-refs/branch-heads/3987@{#801})

i've try to move 'bin' folder to folder 'scraper' to, but with no result. 
So help me please :) thx.

**Comment by xun-0612** [comment]
I modify few lines 807~820 in scraper.py and it works for me :
`  # platform_ = platform.system().lower()
            # chromedriver_versions = {
            #     "linux": os.path.join(
            #         os.getcwd(), CHROMEDRIVER_BINARIES_FOLDER, "chromedriver_linux64",
            #     ),
            #     "darwin": os.path.join(
            #         os.getcwd(), CHROMEDRIVER_BINARIES_FOLDER, "chromedriver_mac64",
            #     ),
            #     "windows": os.path.join(
            #         os.getcwd(), CHROMEDRIVER_BINARIES_FOLDER, "chromedriver_win32.exe",
            #     ),
            # }
            driver = webdriver.Chrome(options=options)`

**Comment by JoseJMJV** [comment]
Hi @DanielOberlechner @meetgyn @hungnt31 

I also have the same problem, 
"Starting Scraping...
Kindly replace the Chrome Web Driver with the latest one from http://chromedriver.chromium.org/downloads and also make sure you have the latest Chrome Browser version.
Your OS: linux"

My ChromeDriver version is  _81.0.4044.69 (6813546031a4bc83f717a2ef7cd4ac6ec1199132-refs/branch-heads/4044@{#776})_, and my Google Chrome version is _81.0.4044.92_

I am using 5.2.0-kali2-amd64 kernel.

I have also tried the previous comment from @xun-0612 , but it didn't run

Please, help me if you were able to resolve it.
Thanks in advance!

**Comment by DanielOberlechner** [comment]
Hi guys,
I have a good idea:
There is a python package named webdriver-manager.
What does this package?

It searches the newest chrome version and auto downloads it and so you don't have to deal with the manual update/download from the chrome package ...

If someone of you guys maybe have time to implement it?
I have 2-3 free days where I maybe have time to implement it if no one else can do it ... 

@harismuneer would it be possible to integrate a pull request?

Greets,
Daniel Oberlechner :)

**Comment by harismuneer** [comment]
### 📢 Important Announcement: UFS 2.0 (with support for latest Facebook UI)

Hi guys! The exclusive version of **UFS 2.0** supports scraping for the latest Facebook UI along with many powerful features, much better organization through CSV (Excel-like) file format, bug fixes, and multiple browser support. You can get exclusive access here: 

#### **[Buy UFS 2.0](https://tinyurl.com/UFS-NEW)** 

Building the new version has been a tough technical challenge and I have spent a considerable amount of time and effort on building it. Therefore, kindly support by purchasing it from the link shared [above.](https://tinyurl.com/UFS-NEW) 

<hr>
You can also share small donations through these links:


- <a href="https://buy.paddle.com/product/638653"><b>Platinum (99.99$)</b> -> 2 hours of development<a/>
- <a href="https://buy.paddle.com/product/638651"><b>Gold (49.99$)</b> -> 1 hour of development</a>
- <a href="https://buy.paddle.com/product/638654"><b>Silver (19.99$)</b> -> 30 minutes of development</a>

_If **considerable support is shown through the above donations then I will release the version for the general public** after some time as I want to keep this software open-sourced. So, now is the time for all those folks who benefited from the tool to support its reach for a wider audience :)_
