### ISSUE TITLE
During handling of the above exception, another exception occurred

### ISSUE THREAD

**Issue by moacyrsalim** [harismuneer/Ultimate-Facebook-Scraper#79]
I tried to scrape some profiles and I get this error almost each scrape section:

```
Friends..
Exception (scrape_data) 0 Status = 0 <class 'selenium.common.exceptions.NoSuchElementException'>
```

Plus, after i finish it, i receive:

```
Process Completed.
Traceback (most recent call last):
  File "[directory]\project_env\lib\site-packages\pkg_resources\__init__.py", line 2451, in resolve
    return functools.reduce(getattr, self.attrs, module)
AttributeError: module 'scraper.__main__' has no attribute 'scraper'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "[directory]\project_env\Scripts\ultimate-facebook-scraper-script.py", line 11, in <module>
    load_entry_point('ultimate-facebook-scraper', 'console_scripts', 'ultimate-facebook-scraper')()
  File "[directory]\project_env\lib\site-packages\pkg_resources\__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "[directory]\project_env\lib\site-packages\pkg_resources\__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "[directory]\project_env\lib\site-packages\pkg_resources\__init__.py", line 2443, in load
    return self.resolve()
  File "[directory]\project_env\lib\site-packages\pkg_resources\__init__.py", line 2453, in resolve
    raise ImportError(str(exc))
ImportError: module 'scraper.__main__' has no attribute 'scraper'
```

**Comment by InsaneJokerr** [comment]
See [You've been temporarily blocked - Facebook #48](https://github.com/harismuneer/Ultimate-Facebook-Scraper/issues/48). This will be a rate limit from Facebook. This is blocking the script from working as it should. We've tried many ways to work around this, but the rate limiter is aggressive. we failed to find a fix.

**Comment by harismuneer** [comment]
### 📢 Important Announcement: UFS 2.0 (with support for latest Facebook UI)

Hi guys! The exclusive version of **UFS 2.0** supports scraping for the latest Facebook UI along with many powerful features, much better organization through CSV (Excel-like) file format, bug fixes, and multiple browser support. You can get exclusive access here: 

#### **[Buy UFS 2.0](https://tinyurl.com/UFS-NEW)** 

Building the new version has been a tough technical challenge and I have spent a considerable amount of time and effort on building it. Therefore, kindly support by purchasing it from the link shared [above.](https://tinyurl.com/UFS-NEW) 

<hr>
You can also share small donations through these links:


- <a href="https://buy.paddle.com/product/638653"><b>Platinum (99.99$)</b> -> 2 hours of development<a/>
- <a href="https://buy.paddle.com/product/638651"><b>Gold (49.99$)</b> -> 1 hour of development</a>
- <a href="https://buy.paddle.com/product/638654"><b>Silver (19.99$)</b> -> 30 minutes of development</a>

_If **considerable support is shown through the above donations then I will release the version for the general public** after some time as I want to keep this software open-sourced. So, now is the time for all those folks who benefited from the tool to support its reach for a wider audience :)_
