### ISSUE TITLE
Error with chromedriver

### ISSUE THREAD

**Issue by regina-avila** [harismuneer/Ultimate-Facebook-Scraper#8]
scraper.py:610: DeprecationWarning: use options instead of chrome_options
  driver = webdriver.Chrome(executable_path="./chromedriver.exe", chrome_options=options)
I'm using a Mac, do I need to change  " if platform.system() == 'Linux':"?

_Originally posted by @regina-avila in https://github.com/harismuneer/Ultimate-Facebook-Scraper/issues/6#issuecomment-443330845_

--------------
Fixed - changed platform.system() == 'Darwin'

**Comment by harismuneer** [comment]
Hi @regina-avila this is just a warning error and it can be ignored. I think the selenium version just got updated. I will update this line of code :) 

There's no need to change that if condition, it runs for Mac too.
