### ISSUE TITLE
Scraping not start Error Kindly replace the Chrome Web Driver with the latest one

### ISSUE THREAD

**Issue by nonmairub** [harismuneer/Ultimate-Facebook-Scraper#81]
I use everything in the latest version.
python 3.8 X
google chrome
web driver
os wins 10
![help](https://user-images.githubusercontent.com/34520333/71362306-47696d80-25c8-11ea-9427-d8f56196ebc9.jpg)

**Comment by MonikaVen** [comment]
Same problem here while trying to build a docker file while having the latest version inside bin/ folder.
Simply using Ubuntu virtual machine with default drivers is working absolutely fantastic.

**Comment by DanielOberlechner** [comment]
http://chromedriver.chromium.org/downloads

Download the correct version for your OS and move the binary to the project folder and give it the correct name !

It is because now google released the new chrome version v80.
And the project itself comes with a older chrome version and so it cannot work.

Just Update this and the scraper should work perfectly!
For any further questions just post here,
I'am happy to help!

Greets,
Daniel Oberlechner :)

**Comment by laurenzm** [comment]
Hello,

same problem and update google driver solve nothing.
Any idee ?

Regards,
Laurent

**Comment by Jackustc** [comment]
This problem is caused by the wrong bin file directory (just move the bin file under the scrapy file directory).  I remember the previous version doesn't have this problem!

**Comment by Whisby25** [comment]
> http://chromedriver.chromium.org/downloads
> 
> Download the correct version for your OS and move the binary to the project folder and give it the correct name !
> 
> It is because now google released the new chrome version v80.
> And the project itself comes with a older chrome version and so it cannot work.
> 
> Just Update this and the scraper should work perfectly!
> For any further questions just post here,
> I'am happy to help!
> 
> Greets,
> Daniel Oberlechner :)

Hey Daniel,
I am using Google Chrome version: 79.0.3945.130 
And OS version: Debian GNU/Linux 10 (buster)

I have followed your advice and downloaded ChromeDriver 79.0.3945.36 for linux 64 and I also replaced the driver in project's bin dir. Unfortunately running the scrapper still gives me the same output:
"Starting Scraping...
Kindly replace the Chrome Web Driver with the latest one from http://chromedriver.chromium.org/downloads and also make sure 
you have the latest Chrome Browser version.
Your OS: linux"

Do you have any more ideas on how I can solve this?

Kind regards,
Michal

**Comment by gangrif** [comment]
im having the exact same problem.  Except I'm on Fedora, Python 3.  Chrome 79, chromedriver 79.  driver is in the right place.  Does not seem to be a path problem as i've added a debug line to the code and the path is coming out correctly.  not sure what else to do here.  Any input would be great.

**Comment by CarlosHRCardoso** [comment]
Its because the relativa path.
The BIN is outside the scrapper folder. You need to move it inside.

cheers

**Comment by harismuneer** [comment]
### 📢 Important Announcement: UFS 2.0 (with support for latest Facebook UI)

Hi guys! The exclusive version of **UFS 2.0** supports scraping for the latest Facebook UI along with many powerful features, much better organization through CSV (Excel-like) file format, bug fixes, and multiple browser support. You can get exclusive access here: 

#### **[Buy UFS 2.0](https://tinyurl.com/UFS-NEW)** 

Building the new version has been a tough technical challenge and I have spent a considerable amount of time and effort on building it. Therefore, kindly support by purchasing it from the link shared [above.](https://tinyurl.com/UFS-NEW) 

<hr>
You can also share small donations through these links:


- <a href="https://buy.paddle.com/product/638653"><b>Platinum (99.99$)</b> -> 2 hours of development<a/>
- <a href="https://buy.paddle.com/product/638651"><b>Gold (49.99$)</b> -> 1 hour of development</a>
- <a href="https://buy.paddle.com/product/638654"><b>Silver (19.99$)</b> -> 30 minutes of development</a>

_If **considerable support is shown through the above donations then I will release the version for the general public** after some time as I want to keep this software open-sourced. So, now is the time for all those folks who benefited from the tool to support its reach for a wider audience :)_
