### ISSUE TITLE
No module named 'yaml'

### ISSUE THREAD

**Issue by avl255** [harismuneer/Ultimate-Facebook-Scraper#85]
Hi there, I'm very new to Python, and I seem to be running into an issue when trying to run this command. I followed the instructions in the "How to Run" section, editing the "credentials.yaml" and "input.txt" files and turning off 2FA on FB. I then opened "scraper.py" and selected Run > Run Module. 

Here's what happened:

'
Python 3.8.2 (v3.8.2:7b3ab5921f, Feb 24 2020, 17:52:18) 
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license()" for more information.
>>> 
= RESTART: /Users/me/Downloads/Ultimate-Facebook-Scraper-2.0/scraper/scraper.py
Traceback (most recent call last):
  File "/Users/me/Downloads/Ultimate-Facebook-Scraper-2.0/scraper/scraper.py", line 6, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
>>> 
'

Here's what I'm using:
 - OS: macOS Catalina (v 10.15.3)
 - Python version: 3.8.2

I'm totally new to this – am I properly running the command? Any insight would be much appreciated. Thanks!

**Comment by arunnane** [comment]
try:

Run the ultimate-facebook-scraper command in the venv/scripts folder.

**Comment by DanielOberlechner** [comment]
@avl255 you don't have the module installerd.
You probably have missed or have had an error during the following steps:
$ git clone https://github.com/harismuneer/Ultimate-Facebook-Scraper.git
$ cd Ultimate-Facebook-Scraper

# Set up a virtual env
$ python3 -m venv venv
$ source venv/bin/activate

# Install Python requirements
$ pip install -e .

Run those commands and try again.
If you need further assistance just write me :)

Greets,
Daniel Oberlechner

**Comment by darklord45** [comment]
i have found this problem solution 
and the solution is in the folder u can find a .yml file move that file to 
scraper folder ur problem will be solved

**Comment by DanielOberlechner** [comment]
> i have found this problem solution
> and the solution is in the folder u can find a .yml file move that file to
> scraper folder ur problem will be solved

Hi,
I'm not sure to 100% but the error was this:
ModuleNotFoundError: No module named 'yaml'

Therefore the python module isn't installed and so the program can't work.
You can prove me wrong but I'm kinda certain about this.

Greets,
Daniel

**Comment by harismuneer** [comment]
### 📢 Important Announcement: UFS 2.0 (with support for latest Facebook UI)

Hi guys! The exclusive version of **UFS 2.0** supports scraping for the latest Facebook UI along with many powerful features, much better organization through CSV (Excel-like) file format, bug fixes, and multiple browser support. You can get exclusive access here: 

#### **[Buy UFS 2.0](https://tinyurl.com/UFS-NEW)** 

Building the new version has been a tough technical challenge and I have spent a considerable amount of time and effort on building it. Therefore, kindly support by purchasing it from the link shared [above.](https://tinyurl.com/UFS-NEW) 

<hr>
You can also share small donations through these links:


- <a href="https://buy.paddle.com/product/638653"><b>Platinum (99.99$)</b> -> 2 hours of development<a/>
- <a href="https://buy.paddle.com/product/638651"><b>Gold (49.99$)</b> -> 1 hour of development</a>
- <a href="https://buy.paddle.com/product/638654"><b>Silver (19.99$)</b> -> 30 minutes of development</a>

_If **considerable support is shown through the above donations then I will release the version for the general public** after some time as I want to keep this software open-sourced. So, now is the time for all those folks who benefited from the tool to support its reach for a wider audience :)_
