### ISSUE TITLE
Does UFS also work with selenium & chromiumdriver versions from the Debian Stetch repositories?

### ISSUE THREAD

**Issue by github-userx** [harismuneer/Ultimate-Facebook-Scraper#9]
Trying to get it to work on Raspbian which is based on Debian Stretch (armhf).

Is it possible to maybe use some of the needed packages for UFS from the debian/ubuntu repositories? (apt-get install)

    python3-selenium
    python-selenium
    chromium (on raspbian the package is named chromium-browser)
    chromium-driver
    chrome-driver
    firefox-driver

I'm not sure if there is even a working version of Chrome for armhf. But chromium should also work, no?

Is python3-selenium the same software like the one from pip/pypi? (Besides pypi being more up-to-date than the debian repos)

PS: absolutely amazing that you created this tool, @harismuneer

**Comment by harismuneer** [comment]
@github-userx, I can't say for sure about the packages available for Debian OS. You can try UFS on it and let me know if you face any issue, then we will look into the matter ;) 

By the way, UFS is a cool name for the scraper 😄 I am glad you found the code useful 👍

**Comment by github-userx** [comment]
Thanks for thecresponse!
I was wondering if I have to edit any of the variables in the code that link to the binaries of chromium/chromium-driver. E.g. On raspuan chromium is called chromium-browser.

Do i have to add info in the line where it says 

  driver =

**Comment by harismuneer** [comment]
@github-userx, yes that's line you have to change if you are using chromium driver binary. Moreover, did you find the relevant packages for Debian OS? If yes, then the code would run perfectly.

Closing this issue for now :)
