### ISSUE TITLE
In the Posts.txt, I cannot see the specific post contents. There is just blank.

### ISSUE THREAD

**Issue by hedyj-1762108** [harismuneer/Ultimate-Facebook-Scraper#91]
In the Posts.txt, I cannot see the specific post contents. There is just blank although there is specific contents posted by the user.

**Comment by osintalex** [comment]
Same problem for me. Everything else seems to be working fine.

**Comment by tridelt** [comment]
same for me :(

**Comment by noamsgl** [comment]
> In the Posts.txt, I cannot see the specific post contents. There is just blank although there is specific contents posted by the user.

Same here

**Comment by nbacademy** [comment]
38/5000
I honestly don't understand a word

Am Di., 19. Mai 2020 um 09:25 Uhr schrieb noamsgl <notifications@github.com
