### ISSUE TITLE
There's some error in log in.

### ISSUE THREAD

**Issue by srmykola** [harismuneer/Ultimate-Facebook-Scraper#94]
Hello guys

I am receiving:

**There's some error in log in.
<class 'NameError'>**

Do you have an idea of how I possibly can fix it?

**Desktop **
 - OS: Ubuntu 18
 - Python version 3.7
 - Chrome web driver version 81.0.4044.69

Best regards, Mykola.

**Comment by kaislar** [comment]
I got also There's some error in log in.
 But <class 'typeError'>

**Comment by bydioeds** [comment]
> I got also There's some error in log in.
> But <class 'typeError'>

Same Error

**Comment by bydioeds** [comment]
@kaislar are you using it in a server?
i think i found out why isn't working, i run it through 'vnc server' and it worked perfectly.
in 'scraper/scraper.py' at line 736 i found a comment about headless but even if is uncommented, it throws another error.

`(<class 'selenium.common.exceptions.NoSuchElementException'>, NoSuchElementException('no such element: Unable to locate element: {"method":"css selector","selector":"[name="email"]"}\n  (Session info: headless chrome=81.0.4044.113)', None, None), <traceback object at 0x7fc3e4fde540>)`

**Comment by osintalex** [comment]
@bydioeds I’m not running in server and have this same issue. Is there an easier workaround than vnc? Thanks for finding that!

**Comment by osintalex** [comment]
Hi guys I just fixed this my end. In the virtual environment navigate to where your chromedrivers are stored (~/.wdm/drivers/chromedriver/81.0.4044.69/linux64) and then delete all the ones that aren’t linux.

Think that error was coming from the chromedrivers not being usable on debian.

**Comment by harismuneer** [comment]
### 📢 Important Announcement: UFS 2.0 (with support for latest Facebook UI)

Hi guys! The exclusive version of **UFS 2.0** supports scraping for the latest Facebook UI along with many powerful features, much better organization through CSV (Excel-like) file format, bug fixes, and multiple browser support. You can get exclusive access here: 

#### **[Buy UFS 2.0](https://tinyurl.com/UFS-NEW)** 

Building the new version has been a tough technical challenge and I have spent a considerable amount of time and effort on building it. Therefore, kindly support by purchasing it from the link shared [above.](https://tinyurl.com/UFS-NEW) 

<hr>
You can also share small donations through these links:


- <a href="https://buy.paddle.com/product/638653"><b>Platinum (99.99$)</b> -> 2 hours of development<a/>
- <a href="https://buy.paddle.com/product/638651"><b>Gold (49.99$)</b> -> 1 hour of development</a>
- <a href="https://buy.paddle.com/product/638654"><b>Silver (19.99$)</b> -> 30 minutes of development</a>

_If **considerable support is shown through the above donations then I will release the version for the general public** after some time as I want to keep this software open-sourced. So, now is the time for all those folks who benefited from the tool to support its reach for a wider audience :)_
